In [3]:
import polars as pl

In [37]:
def clean_edges(df: pl.DataFrame) -> pl.DataFrame:
    return (
        df.select(
            [
                "relation",
                "display_relation",
                "x_id",
                "x_type",
                "x_name",
                "x_source",
                "y_id",
                "y_type",
                "y_name",
                "y_source",
            ]
        )
        .drop_nulls()
        .unique()
        .filter(
            ~(
                (pl.col("x_id") == pl.col("y_id"))
                & (pl.col("x_type") == pl.col("y_type"))
                & (pl.col("x_source") == pl.col("y_source"))
                & (pl.col("x_name") == pl.col("y_name"))
            )
        )
    )

In [39]:
protein_names = catalog.load("bronze.gene_names.protein_names")
drug_protein = catalog.load("bronze.drugbank.drug_protein")

[05/27/25 00:49:05] INFO     Loading data from bronze.gene_names.protein_names            ]8;id=934385;file:///home/viti/Documents/repos/personal/hardvard/optimuskg/.venv/lib/python3.12/site-packages/kedro/io/kedro_data_catalog.py\kedro_data_catalog.py]8;;\:]8;id=257867;file:///home/viti/Documents/repos/personal/hardvard/optimuskg/.venv/lib/python3.12/site-packages/kedro/io/kedro_data_catalog.py#757\757]8;;\
                             (CSVDataset)...

                    INFO     Loading data from bronze.drugbank.drug_protein               ]8;id=346864;file:///home/viti/Documents/repos/personal/hardvard/optimuskg/.venv/lib/python3.12/site-packages/kedro/io/kedro_data_catalog.py\kedro_data_catalog.py]8;;\:]8;id=853185;file:///home/viti/Documents/repos/personal/hardvard/optimuskg/.venv/lib/python3.12/site-packages/kedro/io/kedro_data_catalog.py#757\757]8;;\
                             (CSVDataset)...

In [40]:
df_protein_drug = (
    drug_protein.join(
        protein_names, left_on="ncbi_gene_id", right_on="ncbi_id", how="left"
    )
    .rename(
        {
            "drug_bank_id": "x_id",
            "ncbi_gene_id": "y_id",
            "drug_bank_name": "x_name",
            "symbol": "y_name",
        }
    )
    .with_columns(
        [
            pl.lit("drug").alias("x_type"),
            pl.lit("DrugBank").alias("x_source"),
            pl.lit("gene").alias("y_type"),
            pl.lit("NCBI").alias("y_source"),
            pl.col("relation").alias("display_relation"),
            pl.lit("drug_protein").alias("relation"),
        ]
    )
)
df_protein_drug

shape: (26_320, 12)
┌────────────┬────────────┬────────────┬────────────┬───┬──────────┬────────┬──────────┬───────────┐
│ x_id       ┆ relation   ┆ y_id       ┆ uniprot_na ┆ … ┆ x_source ┆ y_type ┆ y_source ┆ display_r │
│ ---        ┆ ---        ┆ ---        ┆ me         ┆   ┆ ---      ┆ ---    ┆ ---      ┆ elation   │
│ str        ┆ str        ┆ str        ┆ ---        ┆   ┆ str      ┆ str    ┆ str      ┆ ---       │
│            ┆            ┆            ┆ str        ┆   ┆          ┆        ┆          ┆ str       │
╞════════════╪════════════╪════════════╪════════════╪═══╪══════════╪════════╪══════════╪═══════════╡
│ DRUGBANK:D ┆ drug_prote ┆ NCBIGene:2 ┆ Coagulatio ┆ … ┆ DrugBank ┆ gene   ┆ NCBI     ┆ carrier   │
│ B09130     ┆ in         ┆ 157        ┆ n factor   ┆   ┆          ┆        ┆          ┆           │
│            ┆            ┆            ┆ VIII       ┆   ┆          ┆        ┆          ┆           │
│ DRUGBANK:D ┆ drug_prote ┆ NCBIGene:2 ┆ Coagulatio ┆ … ┆ DrugBank ┆ gene   ┆ NCBI     ┆ carrier   │
│ B09130     ┆ in         ┆ 153        ┆ n factor V ┆   ┆          ┆        ┆          ┆           │
│ DRUGBANK:D ┆ drug_prote ┆ NCBIGene:3 ┆ Hemoglobin ┆ … ┆ DrugBank ┆ gene   ┆ NCBI     ┆ carrier   │
│ B09140     ┆ in         ┆ 039        ┆ subunit    ┆   ┆          ┆        ┆          ┆           │
│            ┆            ┆            ┆ alpha      ┆   ┆          ┆        ┆          ┆           │
│ DRUGBANK:D ┆ drug_prote ┆ NCBIGene:3 ┆ Hemoglobin ┆ … ┆ DrugBank ┆ gene   ┆ NCBI     ┆ carrier   │
│ B09140     ┆ in         ┆ 040        ┆ subunit    ┆   ┆          ┆        ┆          ┆           │
│            ┆            ┆            ┆ alpha      ┆   ┆          ┆        ┆          ┆           │
│ DRUGBANK:D ┆ drug_prote ┆ NCBIGene:8 ┆ Corticoste ┆ … ┆ DrugBank ┆ gene   ┆ NCBI     ┆ carrier   │
│ B00180     ┆ in         ┆ 66         ┆ roid-bindi ┆   ┆          ┆        ┆          ┆           │
│            ┆            ┆            ┆ ng         ┆   ┆          ┆        ┆          ┆           │
│            ┆            ┆            ┆ globuli…   ┆   ┆          ┆        ┆          ┆           │
│ …          ┆ …          ┆ …          ┆ …          ┆ … ┆ …        ┆ …      ┆ …        ┆ …         │
│ DRUGBANK:D ┆ drug_prote ┆ NCBIGene:2 ┆ Zinc trans ┆ … ┆ DrugBank ┆ gene   ┆ NCBI     ┆ transport │
│ B14548     ┆ in         ┆ 01266      ┆ porter     ┆   ┆          ┆        ┆          ┆ er        │
│            ┆            ┆            ┆ ZIP11      ┆   ┆          ┆        ┆          ┆           │
│ DRUGBANK:D ┆ drug_prote ┆ NCBIGene:5 ┆ Zinc trans ┆ … ┆ DrugBank ┆ gene   ┆ NCBI     ┆ transport │
│ B14533     ┆ in         ┆ 5676       ┆ porter 6   ┆   ┆          ┆        ┆          ┆ er        │
│ DRUGBANK:D ┆ drug_prote ┆ NCBIGene:5 ┆ Zinc trans ┆ … ┆ DrugBank ┆ gene   ┆ NCBI     ┆ transport │
│ B14548     ┆ in         ┆ 5676       ┆ porter 6   ┆   ┆          ┆        ┆          ┆ er        │
│ DRUGBANK:D ┆ drug_prote ┆ NCBIGene:3 ┆ Aquaporin- ┆ … ┆ DrugBank ┆ gene   ┆ NCBI     ┆ transport │
│ B09462     ┆ in         ┆ 64         ┆ 7          ┆   ┆          ┆        ┆          ┆ er        │
│ DRUGBANK:D ┆ drug_prote ┆ NCBIGene:3 ┆ Aquaporin- ┆ … ┆ DrugBank ┆ gene   ┆ NCBI     ┆ transport │
│ B09462     ┆ in         ┆ 66         ┆ 9          ┆   ┆          ┆        ┆          ┆ er        │
└────────────┴────────────┴────────────┴────────────┴───┴──────────┴────────┴──────────┴───────────┘

In [41]:
clean_edges(df_protein_drug)

shape: (25_754, 10)
┌─────────────┬─────────────┬─────────────┬────────┬───┬─────────────┬────────┬─────────┬──────────┐
│ relation    ┆ display_rel ┆ x_id        ┆ x_type ┆ … ┆ y_id        ┆ y_type ┆ y_name  ┆ y_source │
│ ---         ┆ ation       ┆ ---         ┆ ---    ┆   ┆ ---         ┆ ---    ┆ ---     ┆ ---      │
│ str         ┆ ---         ┆ str         ┆ str    ┆   ┆ str         ┆ str    ┆ str     ┆ str      │
│             ┆ str         ┆             ┆        ┆   ┆             ┆        ┆         ┆          │
╞═════════════╪═════════════╪═════════════╪════════╪═══╪═════════════╪════════╪═════════╪══════════╡
│ drug_protei ┆ target      ┆ DRUGBANK:DB ┆ drug   ┆ … ┆ NCBIGene:17 ┆ gene   ┆ DHFR    ┆ NCBI     │
│ n           ┆             ┆ 03461       ┆        ┆   ┆ 19          ┆        ┆         ┆          │
│ drug_protei ┆ target      ┆ DRUGBANK:DB ┆ drug   ┆ … ┆ NCBIGene:20 ┆ gene   ┆ TUBB    ┆ NCBI     │
│ n           ┆             ┆ 00570       ┆        ┆   ┆ 3068        ┆        ┆         ┆          │
│ drug_protei ┆ enzyme      ┆ DRUGBANK:DB ┆ drug   ┆ … ┆ NCBIGene:15 ┆ gene   ┆ CYP2C19 ┆ NCBI     │
│ n           ┆             ┆ 00574       ┆        ┆   ┆ 57          ┆        ┆         ┆          │
│ drug_protei ┆ target      ┆ DRUGBANK:DB ┆ drug   ┆ … ┆ NCBIGene:54 ┆ gene   ┆ EGLN1   ┆ NCBI     │
│ n           ┆             ┆ 01592       ┆        ┆   ┆ 583         ┆        ┆         ┆          │
│ drug_protei ┆ target      ┆ DRUGBANK:DB ┆ drug   ┆ … ┆ NCBIGene:49 ┆ gene   ┆ NTRK3   ┆ NCBI     │
│ n           ┆             ┆ 15822       ┆        ┆   ┆ 16          ┆        ┆         ┆          │
│ …           ┆ …           ┆ …           ┆ …      ┆ … ┆ …           ┆ …      ┆ …       ┆ …        │
│ drug_protei ┆ target      ┆ DRUGBANK:DB ┆ drug   ┆ … ┆ NCBIGene:21 ┆ gene   ┆ F12     ┆ NCBI     │
│ n           ┆             ┆ 06404       ┆        ┆   ┆ 61          ┆        ┆         ┆          │
│ drug_protei ┆ target      ┆ DRUGBANK:DB ┆ drug   ┆ … ┆ NCBIGene:51 ┆ gene   ┆ PDGFRA  ┆ NCBI     │
│ n           ┆             ┆ 12010       ┆        ┆   ┆ 56          ┆        ┆         ┆          │
│ drug_protei ┆ enzyme      ┆ DRUGBANK:DB ┆ drug   ┆ … ┆ NCBIGene:15 ┆ gene   ┆ CYP3A4  ┆ NCBI     │
│ n           ┆             ┆ 01873       ┆        ┆   ┆ 76          ┆        ┆         ┆          │
│ drug_protei ┆ target      ┆ DRUGBANK:DB ┆ drug   ┆ … ┆ NCBIGene:15 ┆ gene   ┆ ADRA2B  ┆ NCBI     │
│ n           ┆             ┆ 09202       ┆        ┆   ┆ 1           ┆        ┆         ┆          │
│ drug_protei ┆ target      ┆ DRUGBANK:DB ┆ drug   ┆ … ┆ NCBIGene:51 ┆ gene   ┆ PDE4B   ┆ NCBI     │
│ n           ┆             ┆ 01427       ┆        ┆   ┆ 42          ┆        ┆         ┆          │
└─────────────┴─────────────┴─────────────┴────────┴───┴─────────────┴────────┴─────────┴──────────┘

In [42]:
catalog.load("silver.drugbank.drug_drug")

[05/27/25 01:02:10] INFO     Loading data from silver.drugbank.drug_drug (CSVDataset)...  ]8;id=909908;file:///home/viti/Documents/repos/personal/hardvard/optimuskg/.venv/lib/python3.12/site-packages/kedro/io/kedro_data_catalog.py\kedro_data_catalog.py]8;;\:]8;id=497983;file:///home/viti/Documents/repos/personal/hardvard/optimuskg/.venv/lib/python3.12/site-packages/kedro/io/kedro_data_catalog.py#757\757]8;;\

shape: (2_682_157, 10)
┌───────────┬─────────────┬─────────────┬────────┬───┬────────────┬────────┬────────────┬──────────┐
│ relation  ┆ display_rel ┆ x_id        ┆ x_type ┆ … ┆ y_id       ┆ y_type ┆ y_name     ┆ y_source │
│ ---       ┆ ation       ┆ ---         ┆ ---    ┆   ┆ ---        ┆ ---    ┆ ---        ┆ ---      │
│ str       ┆ ---         ┆ str         ┆ str    ┆   ┆ str        ┆ str    ┆ str        ┆ str      │
│           ┆ str         ┆             ┆        ┆   ┆            ┆        ┆            ┆          │
╞═══════════╪═════════════╪═════════════╪════════╪═══╪════════════╪════════╪════════════╪══════════╡
│ drug_drug ┆ synergistic ┆ DRUGBANK:DB ┆ drug   ┆ … ┆ DRUGBANK:D ┆ drug   ┆ Promazine  ┆ DrugBank │
│           ┆ interaction ┆ 00482       ┆        ┆   ┆ B00420     ┆        ┆            ┆          │
│ drug_drug ┆ synergistic ┆ DRUGBANK:DB ┆ drug   ┆ … ┆ DRUGBANK:D ┆ drug   ┆ Benzoctami ┆ DrugBank │
│           ┆ interaction ┆ 06470       ┆        ┆   ┆ B09021     ┆        ┆ ne         ┆          │
│ drug_drug ┆ synergistic ┆ DRUGBANK:DB ┆ drug   ┆ … ┆ DRUGBANK:D ┆ drug   ┆ Pirbuterol ┆ DrugBank │
│           ┆ interaction ┆ 04743       ┆        ┆   ┆ B01291     ┆        ┆            ┆          │
│ drug_drug ┆ synergistic ┆ DRUGBANK:DB ┆ drug   ┆ … ┆ DRUGBANK:D ┆ drug   ┆ Nefiraceta ┆ DrugBank │
│           ┆ interaction ┆ 09190       ┆        ┆   ┆ B13082     ┆        ┆ m          ┆          │
│ drug_drug ┆ synergistic ┆ DRUGBANK:DB ┆ drug   ┆ … ┆ DRUGBANK:D ┆ drug   ┆ Triamcinol ┆ DrugBank │
│           ┆ interaction ┆ 08962       ┆        ┆   ┆ B00620     ┆        ┆ one        ┆          │
│ …         ┆ …           ┆ …           ┆ …      ┆ … ┆ …          ┆ …      ┆ …          ┆ …        │
│ drug_drug ┆ synergistic ┆ DRUGBANK:DB ┆ drug   ┆ … ┆ DRUGBANK:D ┆ drug   ┆ Cyclophosp ┆ DrugBank │
│           ┆ interaction ┆ 13491       ┆        ┆   ┆ B00531     ┆        ┆ hamide     ┆          │
│ drug_drug ┆ synergistic ┆ DRUGBANK:DB ┆ drug   ┆ … ┆ DRUGBANK:D ┆ drug   ┆ Melatonin  ┆ DrugBank │
│           ┆ interaction ┆ 00496       ┆        ┆   ┆ B01065     ┆        ┆            ┆          │
│ drug_drug ┆ synergistic ┆ DRUGBANK:DB ┆ drug   ┆ … ┆ DRUGBANK:D ┆ drug   ┆ Oxacillin  ┆ DrugBank │
│           ┆ interaction ┆ 00718       ┆        ┆   ┆ B00713     ┆        ┆            ┆          │
│ drug_drug ┆ synergistic ┆ DRUGBANK:DB ┆ drug   ┆ … ┆ DRUGBANK:D ┆ drug   ┆ Lofexidine ┆ DrugBank │
│           ┆ interaction ┆ 01203       ┆        ┆   ┆ B04948     ┆        ┆            ┆          │
│ drug_drug ┆ synergistic ┆ DRUGBANK:DB ┆ drug   ┆ … ┆ DRUGBANK:D ┆ drug   ┆ Urelumab   ┆ DrugBank │
│           ┆ interaction ┆ 14952       ┆        ┆   ┆ B12077     ┆        ┆            ┆          │
└───────────┴─────────────┴─────────────┴────────┴───┴────────────┴────────┴────────────┴──────────┘