In [91]:
import re
import polars as pl

In [92]:
ctd_exposure_events = catalog.load("bronze.ctd.ctd_exposure_events")
mondo_xrefs = catalog.load("bronze.ontology.mondo_xrefs")
mondo_terms = catalog.load("bronze.ontology.mondo_terms")
df_exp_disease = ctd_exposure_events.select(
    ["exposure_stressor_name", "exposure_stressor_id", "disease_name", "disease_id"]
)

[06/11/25 22:12:47] INFO     Loading data from bronze.ctd.ctd_exposure_events             ]8;id=3685;file:///home/viti/Documents/repos/personal/hardvard/optimuskg/.venv/lib/python3.12/site-packages/kedro/io/kedro_data_catalog.py\kedro_data_catalog.py]8;;\:]8;id=796191;file:///home/viti/Documents/repos/personal/hardvard/optimuskg/.venv/lib/python3.12/site-packages/kedro/io/kedro_data_catalog.py#757\757]8;;\
                             (CSVDataset)...

                    INFO     Loading data from bronze.ontology.mondo_xrefs                ]8;id=614432;file:///home/viti/Documents/repos/personal/hardvard/optimuskg/.venv/lib/python3.12/site-packages/kedro/io/kedro_data_catalog.py\kedro_data_catalog.py]8;;\:]8;id=571795;file:///home/viti/Documents/repos/personal/hardvard/optimuskg/.venv/lib/python3.12/site-packages/kedro/io/kedro_data_catalog.py#757\757]8;;\
                             (CSVDataset)...

                    INFO     Loading data from bronze.ontology.mondo_terms                ]8;id=929350;file:///home/viti/Documents/repos/personal/hardvard/optimuskg/.venv/lib/python3.12/site-packages/kedro/io/kedro_data_catalog.py\kedro_data_catalog.py]8;;\:]8;id=765278;file:///home/viti/Documents/repos/personal/hardvard/optimuskg/.venv/lib/python3.12/site-packages/kedro/io/kedro_data_catalog.py#757\757]8;;\
                             (CSVDataset)...

In [93]:
mondo_xrefs.head, mondo_terms.head

(
    <bound method DataFrame.head of shape: (134_206, 2)
┌───────────────┬────────────────────────────┐
│ id            ┆ xref_id                    │
│ ---           ┆ ---                        │
│ str           ┆ str                        │
╞═══════════════╪════════════════════════════╡
│ MONDO_0012295 ┆ MEDGEN:91003               │
│ MONDO_0043339 ┆ SCTID:5724005              │
│ MONDO_0014460 ┆ OMIM:616029                │
│ MONDO_0001129 ┆ MEDGEN:233749              │
│ MONDO_0008943 ┆ MEDGEN:349134              │
│ …             ┆ …                          │
│ MONDO_0007737 ┆ icd11.foundation:518723993 │
│ MONDO_0014948 ┆ MEDGEN:934653              │
│ MONDO_0004232 ┆ MEDGEN:274269              │
│ MONDO_0019034 ┆ UMLS:C0266268              │
│ MONDO_0002486 ┆ DOID:3010                  │
└───────────────┴────────────────────────────┘>,
    <bound method DataFrame.head of shape: (30_204, 3)
┌───────────────┬─────────────────────────────────┬───────┐
│ id            ┆ name                            ┆ type  │
│ ---           ┆ ---                             ┆ ---   │
│ str           ┆ str                             ┆ str   │
╞═══════════════╪═════════════════════════════════╪═══════╡
│ MONDO_0007254 ┆ breast cancer                   ┆ CLASS │
│ MONDO_0009513 ┆ laryngo-onycho-cutaneous syndr… ┆ CLASS │
│ MONDO_0012334 ┆ hereditary spastic paraplegia … ┆ CLASS │
│ MONDO_1011140 ┆ choanal atresia, domestic cat   ┆ CLASS │
│ MONDO_0002927 ┆ spindle cell sarcoma            ┆ CLASS │
│ …             ┆ …                               ┆ …     │
│ MONDO_0001104 ┆ toxic diffuse goiter            ┆ CLASS │
│ MONDO_0011627 ┆ autism, susceptibility to, 5    ┆ CLASS │
│ MONDO_0018403 ┆ obsolete female infertility du… ┆ CLASS │
│ MONDO_1012750 ┆ cleft palate, DLX6-related, do… ┆ CLASS │
│ MONDO_0011064 ┆ lethal chondrodysplasia, Selle… ┆ CLASS │
└───────────────┴─────────────────────────────────┴───────┘>
)

In [94]:
mesh_xrefs = mondo_xrefs.filter(pl.col("xref_id").str.contains("MESH"))
mesh_xrefs

shape: (8_234, 2)
┌───────────────┬──────────────┐
│ id            ┆ xref_id      │
│ ---           ┆ ---          │
│ str           ┆ str          │
╞═══════════════╪══════════════╡
│ MONDO_0012305 ┆ MESH:C563695 │
│ MONDO_0010019 ┆ MESH:C562869 │
│ MONDO_0019082 ┆ MESH:D010391 │
│ MONDO_0005564 ┆ MESH:D009373 │
│ MONDO_0007914 ┆ MESH:C563613 │
│ …             ┆ …            │
│ MONDO_0011563 ┆ MESH:C565323 │
│ MONDO_0012944 ┆ MESH:C567245 │
│ MONDO_0007962 ┆ MESH:C562546 │
│ MONDO_0006608 ┆ MESH:D012628 │
│ MONDO_0005554 ┆ MESH:D012216 │
└───────────────┴──────────────┘

In [95]:
df_exp_disease = df_exp_disease.filter(pl.col("disease_id").is_not_null()).with_columns(
    pl.col("disease_id").map_elements(lambda x: f"MESH:{x}").alias("disease_id")
)
df_exp_disease

                    WARNING  /tmp/ipykernel_1136467/2178173091.py:1: MapWithoutReturnDtypeWarning:  ]8;id=835611;file:///usr/lib/python3.12/warnings.py\warnings.py]8;;\:]8;id=825717;file:///usr/lib/python3.12/warnings.py#110\110]8;;\
                             Calling `map_elements` without specifying `return_dtype` can lead to
                             unpredictable results. Specify `return_dtype` to silence this warning.
                               df_exp_disease =
                             df_exp_disease.filter(pl.col("disease_id").is_not_null()).with_columns
                             (

shape: (7_472, 4)
┌─────────────────────────────────┬──────────────────────┬───────────────────────┬──────────────┐
│ exposure_stressor_name          ┆ exposure_stressor_id ┆ disease_name          ┆ disease_id   │
│ ---                             ┆ ---                  ┆ ---                   ┆ ---          │
│ str                             ┆ str                  ┆ str                   ┆ str          │
╞═════════════════════════════════╪══════════════════════╪═══════════════════════╪══════════════╡
│ 1,1,1-trichloroethane           ┆ MESH:C024566         ┆ Amyotrophic Lateral   ┆ MESH:D000690 │
│                                 ┆                      ┆ Sclerosis             ┆              │
│ 1,1,2,2-tetrachloroethane       ┆ MESH:C015530         ┆ Neoplasms             ┆ MESH:D009369 │
│ 1,1,2,2-tetrachloroethane       ┆ MESH:C015530         ┆ Amyotrophic Lateral   ┆ MESH:D000690 │
│                                 ┆                      ┆ Sclerosis             ┆              │
│ 1,2,3,4,7,8-hexachlorodibenzof… ┆ MESH:C051412         ┆ Metabolic Syndrome    ┆ MESH:D024821 │
│ 1,2,3-trichloropropane          ┆ MESH:C009536         ┆ Leukoencephalopathies ┆ MESH:D056784 │
│ …                               ┆ …                    ┆ …                     ┆ …            │
│ Zinc                            ┆ MESH:D015032         ┆ Respiratory Distress  ┆ MESH:D012128 │
│                                 ┆                      ┆ Syndrome              ┆              │
│ Ziram                           ┆ MESH:D015039         ┆ Respiratory Sounds    ┆ MESH:D012135 │
│ Ziram                           ┆ MESH:D015039         ┆ Death                 ┆ MESH:D003643 │
│ Ziram                           ┆ MESH:D015039         ┆ Agricultural Workers' ┆ MESH:D000382 │
│                                 ┆                      ┆ Diseases              ┆              │
│ Ziram                           ┆ MESH:D015039         ┆ Retinal Degeneration  ┆ MESH:D012162 │
└─────────────────────────────────┴──────────────────────┴───────────────────────┴──────────────┘

In [96]:
df_exp_disease = df_exp_disease.join(
    mesh_xrefs, left_on="disease_id", right_on="xref_id", how="left"
)
df_exp_disease

shape: (7_767, 5)
┌──────────────────────┬──────────────────────┬─────────────────────┬──────────────┬───────────────┐
│ exposure_stressor_na ┆ exposure_stressor_id ┆ disease_name        ┆ disease_id   ┆ id            │
│ me                   ┆ ---                  ┆ ---                 ┆ ---          ┆ ---           │
│ ---                  ┆ str                  ┆ str                 ┆ str          ┆ str           │
│ str                  ┆                      ┆                     ┆              ┆               │
╞══════════════════════╪══════════════════════╪═════════════════════╪══════════════╪═══════════════╡
│ 1,1,1-trichloroethan ┆ MESH:C024566         ┆ Amyotrophic Lateral ┆ MESH:D000690 ┆ MONDO_0004976 │
│ e                    ┆                      ┆ Sclerosis           ┆              ┆               │
│ 1,1,2,2-tetrachloroe ┆ MESH:C015530         ┆ Neoplasms           ┆ MESH:D009369 ┆ MONDO_0005070 │
│ thane                ┆                      ┆                     ┆              ┆               │
│ 1,1,2,2-tetrachloroe ┆ MESH:C015530         ┆ Amyotrophic Lateral ┆ MESH:D000690 ┆ MONDO_0004976 │
│ thane                ┆                      ┆ Sclerosis           ┆              ┆               │
│ 1,2,3,4,7,8-hexachlo ┆ MESH:C051412         ┆ Metabolic Syndrome  ┆ MESH:D024821 ┆ MONDO_0011565 │
│ rodibenzof…          ┆                      ┆                     ┆              ┆               │
│ 1,2,3-trichloropropa ┆ MESH:C009536         ┆ Leukoencephalopathi ┆ MESH:D056784 ┆ null          │
│ ne                   ┆                      ┆ es                  ┆              ┆               │
│ …                    ┆ …                    ┆ …                   ┆ …            ┆ …             │
│ Zinc                 ┆ MESH:D015032         ┆ Respiratory         ┆ MESH:D012128 ┆ MONDO_0100130 │
│                      ┆                      ┆ Distress Syndrome   ┆              ┆               │
│ Ziram                ┆ MESH:D015039         ┆ Respiratory Sounds  ┆ MESH:D012135 ┆ null          │
│ Ziram                ┆ MESH:D015039         ┆ Death               ┆ MESH:D003643 ┆ null          │
│ Ziram                ┆ MESH:D015039         ┆ Agricultural        ┆ MESH:D000382 ┆ null          │
│                      ┆                      ┆ Workers' Diseases   ┆              ┆               │
│ Ziram                ┆ MESH:D015039         ┆ Retinal             ┆ MESH:D012162 ┆ MONDO_0004580 │
│                      ┆                      ┆ Degeneration        ┆              ┆               │
└──────────────────────┴──────────────────────┴─────────────────────┴──────────────┴───────────────┘

In [97]:
df_exp_disease = df_exp_disease.join(
    mondo_terms, left_on="id", right_on="id", how="left"
)
df_exp_disease

shape: (7_767, 7)
┌───────────────┬──────────────┬──────────────┬──────────────┬──────────────┬──────────────┬───────┐
│ exposure_stre ┆ exposure_str ┆ disease_name ┆ disease_id   ┆ id           ┆ name         ┆ type  │
│ ssor_name     ┆ essor_id     ┆ ---          ┆ ---          ┆ ---          ┆ ---          ┆ ---   │
│ ---           ┆ ---          ┆ str          ┆ str          ┆ str          ┆ str          ┆ str   │
│ str           ┆ str          ┆              ┆              ┆              ┆              ┆       │
╞═══════════════╪══════════════╪══════════════╪══════════════╪══════════════╪══════════════╪═══════╡
│ 1,1,1-trichlo ┆ MESH:C024566 ┆ Amyotrophic  ┆ MESH:D000690 ┆ MONDO_000497 ┆ amyotrophic  ┆ CLASS │
│ roethane      ┆              ┆ Lateral      ┆              ┆ 6            ┆ lateral      ┆       │
│               ┆              ┆ Sclerosis    ┆              ┆              ┆ sclerosis    ┆       │
│ 1,1,2,2-tetra ┆ MESH:C015530 ┆ Neoplasms    ┆ MESH:D009369 ┆ MONDO_000507 ┆ neoplasm     ┆ CLASS │
│ chloroethane  ┆              ┆              ┆              ┆ 0            ┆              ┆       │
│ 1,1,2,2-tetra ┆ MESH:C015530 ┆ Amyotrophic  ┆ MESH:D000690 ┆ MONDO_000497 ┆ amyotrophic  ┆ CLASS │
│ chloroethane  ┆              ┆ Lateral      ┆              ┆ 6            ┆ lateral      ┆       │
│               ┆              ┆ Sclerosis    ┆              ┆              ┆ sclerosis    ┆       │
│ 1,2,3,4,7,8-h ┆ MESH:C051412 ┆ Metabolic    ┆ MESH:D024821 ┆ MONDO_001156 ┆ metabolic    ┆ CLASS │
│ exachlorodibe ┆              ┆ Syndrome     ┆              ┆ 5            ┆ syndrome X   ┆       │
│ nzof…         ┆              ┆              ┆              ┆              ┆              ┆       │
│ 1,2,3-trichlo ┆ MESH:C009536 ┆ Leukoencepha ┆ MESH:D056784 ┆ null         ┆ null         ┆ null  │
│ ropropane     ┆              ┆ lopathies    ┆              ┆              ┆              ┆       │
│ …             ┆ …            ┆ …            ┆ …            ┆ …            ┆ …            ┆ …     │
│ Zinc          ┆ MESH:D015032 ┆ Respiratory  ┆ MESH:D012128 ┆ MONDO_010013 ┆ adult acute  ┆ CLASS │
│               ┆              ┆ Distress     ┆              ┆ 0            ┆ respiratory  ┆       │
│               ┆              ┆ Syndrome     ┆              ┆              ┆ distre…      ┆       │
│ Ziram         ┆ MESH:D015039 ┆ Respiratory  ┆ MESH:D012135 ┆ null         ┆ null         ┆ null  │
│               ┆              ┆ Sounds       ┆              ┆              ┆              ┆       │
│ Ziram         ┆ MESH:D015039 ┆ Death        ┆ MESH:D003643 ┆ null         ┆ null         ┆ null  │
│ Ziram         ┆ MESH:D015039 ┆ Agricultural ┆ MESH:D000382 ┆ null         ┆ null         ┆ null  │
│               ┆              ┆ Workers'     ┆              ┆              ┆              ┆       │
│               ┆              ┆ Diseases     ┆              ┆              ┆              ┆       │
│ Ziram         ┆ MESH:D015039 ┆ Retinal      ┆ MESH:D012162 ┆ MONDO_000458 ┆ retinal      ┆ CLASS │
│               ┆              ┆ Degeneration ┆              ┆ 0            ┆ degeneration ┆       │
└───────────────┴──────────────┴──────────────┴──────────────┴──────────────┴──────────────┴───────┘

In [98]:
df_exp_disease = (
    df_exp_disease.rename(
        {
            "exposure_stressor_id": "x_id",
            "exposure_stressor_name": "x_name",
            "disease_id": "y_id",
            "disease_name": "y_name",
        }
    )
    .with_columns(
        [
            pl.lit("exposure").alias("x_type"),
            pl.lit("CTD").alias("x_source"),
            pl.lit("disease").alias("y_type"),
            pl.lit("MONDO").alias("y_source"),
            pl.lit("exposure_disease").alias("relation"),
            pl.lit("linked to").alias("relation_type"),
        ]
    )
    .select(
        [
            "relation",
            "relation_type",
            "x_id",
            "x_type",
            "x_name",
            "x_source",
            "y_id",
            "y_type",
            "y_name",
            "y_source",
        ]
    )
)
df_exp_disease

shape: (7_767, 10)
┌────────────┬────────────┬────────────┬──────────┬───┬───────────┬─────────┬───────────┬──────────┐
│ relation   ┆ relation_t ┆ x_id       ┆ x_type   ┆ … ┆ y_id      ┆ y_type  ┆ y_name    ┆ y_source │
│ ---        ┆ ype        ┆ ---        ┆ ---      ┆   ┆ ---       ┆ ---     ┆ ---       ┆ ---      │
│ str        ┆ ---        ┆ str        ┆ str      ┆   ┆ str       ┆ str     ┆ str       ┆ str      │
│            ┆ str        ┆            ┆          ┆   ┆           ┆         ┆           ┆          │
╞════════════╪════════════╪════════════╪══════════╪═══╪═══════════╪═════════╪═══════════╪══════════╡
│ exposure_d ┆ linked to  ┆ MESH:C0245 ┆ exposure ┆ … ┆ MESH:D000 ┆ disease ┆ Amyotroph ┆ MONDO    │
│ isease     ┆            ┆ 66         ┆          ┆   ┆ 690       ┆         ┆ ic        ┆          │
│            ┆            ┆            ┆          ┆   ┆           ┆         ┆ Lateral   ┆          │
│            ┆            ┆            ┆          ┆   ┆           ┆         ┆ Sclerosis ┆          │
│ exposure_d ┆ linked to  ┆ MESH:C0155 ┆ exposure ┆ … ┆ MESH:D009 ┆ disease ┆ Neoplasms ┆ MONDO    │
│ isease     ┆            ┆ 30         ┆          ┆   ┆ 369       ┆         ┆           ┆          │
│ exposure_d ┆ linked to  ┆ MESH:C0155 ┆ exposure ┆ … ┆ MESH:D000 ┆ disease ┆ Amyotroph ┆ MONDO    │
│ isease     ┆            ┆ 30         ┆          ┆   ┆ 690       ┆         ┆ ic        ┆          │
│            ┆            ┆            ┆          ┆   ┆           ┆         ┆ Lateral   ┆          │
│            ┆            ┆            ┆          ┆   ┆           ┆         ┆ Sclerosis ┆          │
│ exposure_d ┆ linked to  ┆ MESH:C0514 ┆ exposure ┆ … ┆ MESH:D024 ┆ disease ┆ Metabolic ┆ MONDO    │
│ isease     ┆            ┆ 12         ┆          ┆   ┆ 821       ┆         ┆ Syndrome  ┆          │
│ exposure_d ┆ linked to  ┆ MESH:C0095 ┆ exposure ┆ … ┆ MESH:D056 ┆ disease ┆ Leukoence ┆ MONDO    │
│ isease     ┆            ┆ 36         ┆          ┆   ┆ 784       ┆         ┆ phalopath ┆          │
│            ┆            ┆            ┆          ┆   ┆           ┆         ┆ ies       ┆          │
│ …          ┆ …          ┆ …          ┆ …        ┆ … ┆ …         ┆ …       ┆ …         ┆ …        │
│ exposure_d ┆ linked to  ┆ MESH:D0150 ┆ exposure ┆ … ┆ MESH:D012 ┆ disease ┆ Respirato ┆ MONDO    │
│ isease     ┆            ┆ 32         ┆          ┆   ┆ 128       ┆         ┆ ry        ┆          │
│            ┆            ┆            ┆          ┆   ┆           ┆         ┆ Distress  ┆          │
│            ┆            ┆            ┆          ┆   ┆           ┆         ┆ Syndrome  ┆          │
│ exposure_d ┆ linked to  ┆ MESH:D0150 ┆ exposure ┆ … ┆ MESH:D012 ┆ disease ┆ Respirato ┆ MONDO    │
│ isease     ┆            ┆ 39         ┆          ┆   ┆ 135       ┆         ┆ ry Sounds ┆          │
│ exposure_d ┆ linked to  ┆ MESH:D0150 ┆ exposure ┆ … ┆ MESH:D003 ┆ disease ┆ Death     ┆ MONDO    │
│ isease     ┆            ┆ 39         ┆          ┆   ┆ 643       ┆         ┆           ┆          │
│ exposure_d ┆ linked to  ┆ MESH:D0150 ┆ exposure ┆ … ┆ MESH:D000 ┆ disease ┆ Agricultu ┆ MONDO    │
│ isease     ┆            ┆ 39         ┆          ┆   ┆ 382       ┆         ┆ ral       ┆          │
│            ┆            ┆            ┆          ┆   ┆           ┆         ┆ Workers'  ┆          │
│            ┆            ┆            ┆          ┆   ┆           ┆         ┆ Diseases  ┆          │
│ exposure_d ┆ linked to  ┆ MESH:D0150 ┆ exposure ┆ … ┆ MESH:D012 ┆ disease ┆ Retinal   ┆ MONDO    │
│ isease     ┆            ┆ 39         ┆          ┆   ┆ 162       ┆         ┆ Degenerat ┆          │
│            ┆            ┆            ┆          ┆   ┆           ┆         ┆ ion       ┆          │
└────────────┴────────────┴────────────┴──────────┴───┴───────────┴─────────┴───────────┴──────────┘