In [2]:
import polars as pl

In [8]:
go_relations = catalog.load("bronze.ontology.go_relations")
go_terms = catalog.load("bronze.ontology.go_terms")

[06/24/25 20:24:13] INFO     Loading data from bronze.ontology.go_relations               ]8;id=788600;file:///home/viti/Documents/repos/personal/hardvard/optimuskg/.venv/lib/python3.12/site-packages/kedro/io/kedro_data_catalog.py\kedro_data_catalog.py]8;;\:]8;id=433263;file:///home/viti/Documents/repos/personal/hardvard/optimuskg/.venv/lib/python3.12/site-packages/kedro/io/kedro_data_catalog.py#757\757]8;;\
                             (CSVDataset)...

                    INFO     Loading data from bronze.ontology.go_terms (CSVDataset)...   ]8;id=804171;file:///home/viti/Documents/repos/personal/hardvard/optimuskg/.venv/lib/python3.12/site-packages/kedro/io/kedro_data_catalog.py\kedro_data_catalog.py]8;;\:]8;id=337869;file:///home/viti/Documents/repos/personal/hardvard/optimuskg/.venv/lib/python3.12/site-packages/kedro/io/kedro_data_catalog.py#757\757]8;;\

In [10]:
go_terms

shape: (51_676, 3)
┌────────────┬─────────────────────────────────┬────────────────────┐
│ id         ┆ name                            ┆ type               │
│ ---        ┆ ---                             ┆ ---                │
│ str        ┆ str                             ┆ str                │
╞════════════╪═════════════════════════════════╪════════════════════╡
│ GO_0072278 ┆ metanephric comma-shaped body … ┆ biological_process │
│ GO_0006312 ┆ mitotic recombination           ┆ biological_process │
│ GO_0061449 ┆ olfactory bulb tufted cell dev… ┆ biological_process │
│ GO_1903415 ┆ flavonoid transport from endop… ┆ biological_process │
│ GO_1902657 ┆ protein localization to prospo… ┆ biological_process │
│ …          ┆ …                               ┆ …                  │
│ GO_0018046 ┆ obsolete C-terminal peptidyl-m… ┆ biological_process │
│ GO_0061854 ┆ positive regulation of neurobl… ┆ biological_process │
│ GO_0072613 ┆ null                            ┆ CLASS              │
│ GO_1901716 ┆ negative regulation of gamma-a… ┆ biological_process │
│ GO_1902230 ┆ negative regulation of intrins… ┆ biological_process │
└────────────┴─────────────────────────────────┴────────────────────┘

In [11]:
go_relations

shape: (82_354, 3)
┌────────────┬───────────────┬────────────┐
│ tail       ┆ edge_type     ┆ head       │
│ ---        ┆ ---           ┆ ---        │
│ str        ┆ str           ┆ str        │
╞════════════╪═══════════════╪════════════╡
│ GO_0000001 ┆ is_a          ┆ GO_0048308 │
│ GO_0000001 ┆ is_a          ┆ GO_0048311 │
│ GO_0000001 ┆ GOREL_0002003 ┆ GO_0005739 │
│ GO_0000002 ┆ is_a          ┆ GO_0007005 │
│ GO_0000006 ┆ is_a          ┆ GO_0005385 │
│ …          ┆ …             ┆ …          │
│ GO_2001316 ┆ is_a          ┆ GO_0120254 │
│ GO_2001317 ┆ is_a          ┆ GO_0034309 │
│ GO_2001317 ┆ is_a          ┆ GO_0042181 │
│ GO_2001317 ┆ is_a          ┆ GO_0120255 │
│ GO_2001317 ┆ is_a          ┆ GO_2001316 │
└────────────┴───────────────┴────────────┘

In [20]:
cc = go_terms.filter(pl.col("type") == "cellular_component")

df_go_edges = go_relations.rename({"tail": "x_id", "head": "y_id"})

(
    df_go_edges.join(
        cc.select(["id", "name"]), left_on="x_id", right_on="id", how="inner"
    )
    .rename({"name": "x_name"})
    .join(cc.select(["id", "name"]), left_on="y_id", right_on="id", how="inner")
    .rename({"name": "y_name"})
    .with_columns(
        [
            pl.lit("cellular_component").alias("x_type"),
            pl.lit("GO").alias("x_source"),
            pl.lit("cellular_component").alias("y_type"),
            pl.lit("GO").alias("y_source"),
            pl.lit("cellcomp_cellcomp").alias("relation"),
            pl.lit("parent-child").alias("relation_type"),
        ]
    )
    .with_columns(
        pl.concat_list([pl.col("x_id"), pl.col("y_id")]).list.sort().alias("sorted_ids")
    )
    .unique("sorted_ids", keep="first")
    .drop("sorted_ids")
    .select(
        [
            "relation",
            "relation_type",
            "x_id",
            "x_type",
            "x_name",
            "x_source",
            "y_id",
            "y_type",
            "y_name",
            "y_source",
        ]
    )
)

shape: (6_637, 10)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ relation  ┆ relation_ ┆ x_id      ┆ x_type    ┆ … ┆ y_id      ┆ y_type    ┆ y_name    ┆ y_source │
│ ---       ┆ type      ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ str       ┆ ---       ┆ str       ┆ str       ┆   ┆ str       ┆ str       ┆ str       ┆ str      │
│           ┆ str       ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ cellcomp_ ┆ parent-ch ┆ GO_006164 ┆ cellular_ ┆ … ┆ GO_011016 ┆ cellular_ ┆ cellular  ┆ GO       │
│ cellcomp  ┆ ild       ┆ 5         ┆ component ┆   ┆ 5         ┆ component ┆ anatomica ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ l         ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ structure ┆          │
│ cellcomp_ ┆ parent-ch ┆ GO_006207 ┆ cellular_ ┆ … ┆ GO_000573 ┆ cellular_ ┆ cytoplasm ┆ GO       │
│ cellcomp  ┆ ild       ┆ 3         ┆ component ┆   ┆ 7         ┆ component ┆           ┆          │
│ cellcomp_ ┆ parent-ch ┆ GO_199046 ┆ cellular_ ┆ … ┆ GO_199092 ┆ cellular_ ┆ PET       ┆ GO       │
│ cellcomp  ┆ ild       ┆ 9         ┆ component ┆   ┆ 3         ┆ component ┆ complex   ┆          │
│ cellcomp_ ┆ parent-ch ┆ GO_001982 ┆ cellular_ ┆ … ┆ GO_000577 ┆ cellular_ ┆ peroxisom ┆ GO       │
│ cellcomp  ┆ ild       ┆ 3         ┆ component ┆   ┆ 7         ┆ component ┆ e         ┆          │
│ cellcomp_ ┆ parent-ch ┆ GO_006163 ┆ cellular_ ┆ … ┆ GO_003450 ┆ cellular_ ┆ chromosom ┆ GO       │
│ cellcomp  ┆ ild       ┆ 8         ┆ component ┆   ┆ 6         ┆ component ┆ e, centro ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ meric     ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ core d…   ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ cellcomp_ ┆ parent-ch ┆ GO_001711 ┆ cellular_ ┆ … ┆ GO_003320 ┆ cellular_ ┆ DNA       ┆ GO       │
│ cellcomp  ┆ ild       ┆ 7         ┆ component ┆   ┆ 2         ┆ component ┆ helicase  ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ complex   ┆          │
│ cellcomp_ ┆ parent-ch ┆ GO_000093 ┆ cellular_ ┆ … ┆ GO_000077 ┆ cellular_ ┆ kinetocho ┆ GO       │
│ cellcomp  ┆ ild       ┆ 9         ┆ component ┆   ┆ 6         ┆ component ┆ re        ┆          │
│ cellcomp_ ┆ parent-ch ┆ GO_001900 ┆ cellular_ ┆ … ┆ GO_003146 ┆ cellular_ ┆ cullin-RI ┆ GO       │
│ cellcomp  ┆ ild       ┆ 5         ┆ component ┆   ┆ 1         ┆ component ┆ NG        ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ ubiquitin ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ ligase c… ┆          │
│ cellcomp_ ┆ parent-ch ┆ GO_009889 ┆ cellular_ ┆ … ┆ GO_009963 ┆ cellular_ ┆ postsynap ┆ GO       │
│ cellcomp  ┆ ild       ┆ 2         ┆ component ┆   ┆ 4         ┆ component ┆ tic speci ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ alization ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ me…       ┆          │
│ cellcomp_ ┆ parent-ch ┆ GO_001000 ┆ cellular_ ┆ … ┆ GO_009856 ┆ cellular_ ┆ cytoplasm ┆ GO       │
│ cellcomp  ┆ ild       ┆ 9         ┆ component ┆   ┆ 2         ┆ component ┆ ic side   ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ of        ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ membrane  ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘