In [10]:
import re
import polars as pl

In [3]:
evidence_ds_names = catalog.filter(name_regex=re.compile("^silver.opentargets"))
evidence_ds_names

[
    'silver.opentargets.disease_to_phenotype',
    'silver.opentargets.opentargets_edges',
    'silver.opentargets.evidence.cancer_gene_census',
    'silver.opentargets.evidence.chembl_drug_disease',
    'silver.opentargets.evidence.chembl_drug_gene',
    'silver.opentargets.evidence.clingen',
    'silver.opentargets.evidence.crispr',
    'silver.opentargets.evidence.crispr_screen',
    'silver.opentargets.evidence.expression_atlas',
    'silver.opentargets.evidence.gene_burden',
    'silver.opentargets.evidence.gene2phenotype',
    'silver.opentargets.evidence.genomics_england',
    'silver.opentargets.evidence.intogen',
    'silver.opentargets.evidence.orphanet',
    'silver.opentargets.evidence.progeny',
    'silver.opentargets.evidence.reactome',
    'silver.opentargets.evidence.slapenrich',
    'silver.opentargets.evidence.sysbio',
    'silver.opentargets.evidence.uniprot_literature'
]

In [5]:
opentargets_edges = catalog.load("silver.opentargets.opentargets_edges")

[05/30/25 11:52:38] INFO     Loading data from silver.opentargets.opentargets_edges       ]8;id=311699;file:///home/viti/Documents/repos/harvard/optimuskg/.venv/lib/python3.12/site-packages/kedro/io/kedro_data_catalog.py\kedro_data_catalog.py]8;;\:]8;id=582768;file:///home/viti/Documents/repos/harvard/optimuskg/.venv/lib/python3.12/site-packages/kedro/io/kedro_data_catalog.py#757\757]8;;\
                             (CSVDataset)...

In [11]:
opentargets_edges.filter(pl.col("y_type") == "gene")

shape: (234_826, 10)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ x_id      ┆ y_id      ┆ relation  ┆ display_r ┆ … ┆ x_name    ┆ x_source  ┆ y_name    ┆ y_source │
│ ---       ┆ ---       ┆ ---       ┆ elation   ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ str       ┆ str       ┆ str       ┆ ---       ┆   ┆ str       ┆ str       ┆ str       ┆ str      │
│           ┆           ┆           ┆ str       ┆   ┆           ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ CHEMBL100 ┆ ENSG00000 ┆ drug_prot ┆ target    ┆ … ┆ CETIRIZIN ┆ histamine ┆ opentarge ┆ opentarg │
│ 0         ┆ 196639    ┆ ein       ┆           ┆   ┆ E         ┆ receptor  ┆ ts        ┆ ets      │
│           ┆           ┆           ┆           ┆   ┆           ┆ H1        ┆           ┆          │
│ CHEMBL100 ┆ ENSG00000 ┆ drug_prot ┆ target    ┆ … ┆ LEVOSALBU ┆ adrenocep ┆ opentarge ┆ opentarg │
│ 2         ┆ 169252    ┆ ein       ┆           ┆   ┆ TAMOL     ┆ tor beta  ┆ ts        ┆ ets      │
│           ┆           ┆           ┆           ┆   ┆           ┆ 2         ┆           ┆          │
│ CHEMBL100 ┆ ENSG00000 ┆ drug_prot ┆ target    ┆ … ┆ DOXYLAMIN ┆ histamine ┆ opentarge ┆ opentarg │
│ 4         ┆ 196639    ┆ ein       ┆           ┆   ┆ E         ┆ receptor  ┆ ts        ┆ ets      │
│           ┆           ┆           ┆           ┆   ┆           ┆ H1        ┆           ┆          │
│ CHEMBL100 ┆ ENSG00000 ┆ drug_prot ┆ target    ┆ … ┆ REMIFENTA ┆ opioid    ┆ opentarge ┆ opentarg │
│ 5         ┆ 112038    ┆ ein       ┆           ┆   ┆ NIL       ┆ receptor  ┆ ts        ┆ ets      │
│           ┆           ┆           ┆           ┆   ┆           ┆ mu 1      ┆           ┆          │
│ CHEMBL100 ┆ ENSG00000 ┆ drug_prot ┆ target    ┆ … ┆ BEPRIDIL  ┆ calcium   ┆ opentarge ┆ opentarg │
│ 8         ┆ 006116    ┆ ein       ┆           ┆   ┆           ┆ voltage-g ┆ ts        ┆ ets      │
│           ┆           ┆           ┆           ┆   ┆           ┆ ated      ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ channel … ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ MONDO_800 ┆ ENSG00000 ┆ disease_p ┆ associate ┆ … ┆ neurologi ┆ peptidyl- ┆ opentarge ┆ opentarg │
│ 0012      ┆ 141378    ┆ rotein    ┆ d with    ┆   ┆ c, endocr ┆ tRNA      ┆ ts        ┆ ets      │
│           ┆           ┆           ┆           ┆   ┆ ine, and  ┆ hydrolase ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ pan…      ┆ 2         ┆           ┆          │
│ Orphanet_ ┆ ENSG00000 ┆ disease_p ┆ associate ┆ … ┆ Freeman-S ┆ sodium    ┆ opentarge ┆ opentarg │
│ 2053      ┆ 102452    ┆ rotein    ┆ d with    ┆   ┆ heldon    ┆ leak      ┆ ts        ┆ ets      │
│           ┆           ┆           ┆           ┆   ┆ syndrome  ┆ channel,  ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ non-selec ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ …         ┆           ┆          │
│ Orphanet_ ┆ ENSG00000 ┆ disease_p ┆ associate ┆ … ┆ Freeman-S ┆ myosin    ┆ opentarge ┆ opentarg │
│ 2053      ┆ 109063    ┆ rotein    ┆ d with    ┆   ┆ heldon    ┆ heavy     ┆ ts        ┆ ets      │
│           ┆           ┆           ┆           ┆   ┆ syndrome  ┆ chain 3   ┆           ┆          │
│ Orphanet_ ┆ ENSG00000 ┆ disease_p ┆ associate ┆ … ┆ WHIM      ┆ C-X-C     ┆ opentarge ┆ opentarg │
│ 51636     ┆ 121966    ┆ rotein    ┆ d with    ┆   ┆ syndrome  ┆ motif     ┆ ts        ┆ ets      │
│           ┆           ┆           ┆           ┆   ┆           ┆ chemokine ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ receptor… ┆           ┆          │
│ Orphanet_ ┆ ENSG00000 ┆ disease_p ┆ associate ┆ … ┆ PEHO-like ┆ coiled-co ┆ opentarge ┆ opentarg │
│ 99807     ┆ 115355    ┆ rotein    ┆ d with    ┆   ┆ syndrome  ┆ il domain ┆ ts        ┆ ets      │
│           ┆           ┆           ┆           ┆   ┆           ┆ containin ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ g …       ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [12]:
opentargets_edges.filter(pl.col("x_type") == "gene")

shape: (234_826, 10)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ x_id      ┆ y_id      ┆ relation  ┆ display_r ┆ … ┆ x_name    ┆ x_source  ┆ y_name    ┆ y_source │
│ ---       ┆ ---       ┆ ---       ┆ elation   ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ str       ┆ str       ┆ str       ┆ ---       ┆   ┆ str       ┆ str       ┆ str       ┆ str      │
│           ┆           ┆           ┆ str       ┆   ┆           ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ ENSG00000 ┆ EFO_00001 ┆ disease_p ┆ expressio ┆ … ┆ tetraspan ┆ MALT      ┆ opentarge ┆ opentarg │
│ 000003    ┆ 91        ┆ rotein_po ┆ n upregul ┆   ┆ in 6      ┆ lymphoma  ┆ ts        ┆ ets      │
│           ┆           ┆ sitive    ┆ ated      ┆   ┆           ┆           ┆           ┆          │
│ ENSG00000 ┆ EFO_00001 ┆ disease_p ┆ expressio ┆ … ┆ tetraspan ┆ oral      ┆ opentarge ┆ opentarg │
│ 000003    ┆ 99        ┆ rotein_ne ┆ n downreg ┆   ┆ in 6      ┆ squamous  ┆ ts        ┆ ets      │
│           ┆           ┆ gative    ┆ ulated    ┆   ┆           ┆ cell      ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ carcinoma ┆           ┆          │
│ ENSG00000 ┆ EFO_00002 ┆ disease_p ┆ expressio ┆ … ┆ tetraspan ┆ astrocyto ┆ opentarge ┆ opentarg │
│ 000003    ┆ 72        ┆ rotein_po ┆ n upregul ┆   ┆ in 6      ┆ ma        ┆ ts        ┆ ets      │
│           ┆           ┆ sitive    ┆ ated      ┆   ┆           ┆           ┆           ┆          │
│ ENSG00000 ┆ EFO_00003 ┆ disease_p ┆ expressio ┆ … ┆ tetraspan ┆ breast    ┆ opentarge ┆ opentarg │
│ 000003    ┆ 05        ┆ rotein_ne ┆ n downreg ┆   ┆ in 6      ┆ carcinoma ┆ ts        ┆ ets      │
│           ┆           ┆ gative    ┆ ulated    ┆   ┆           ┆           ┆           ┆          │
│ ENSG00000 ┆ EFO_00005 ┆ disease_p ┆ expressio ┆ … ┆ tetraspan ┆ glioblast ┆ opentarge ┆ opentarg │
│ 000003    ┆ 19        ┆ rotein_po ┆ n upregul ┆   ┆ in 6      ┆ oma multi ┆ ts        ┆ ets      │
│           ┆           ┆ sitive    ┆ ated      ┆   ┆           ┆ forme     ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ ENSG00000 ┆ EFO_00003 ┆ disease_p ┆ associate ┆ … ┆ acetylser ┆ cutaneous ┆ opentarge ┆ opentarg │
│ 292336    ┆ 89        ┆ rotein    ┆ d with    ┆   ┆ otonin    ┆ melanoma  ┆ ts        ┆ ets      │
│           ┆           ┆           ┆           ┆   ┆ O-methylt ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ ransf…    ┆           ┆           ┆          │
│ ENSG00000 ┆ EFO_00005 ┆ disease_p ┆ associate ┆ … ┆ acetylser ┆ lung aden ┆ opentarge ┆ opentarg │
│ 292336    ┆ 71        ┆ rotein    ┆ d with    ┆   ┆ otonin    ┆ ocarcinom ┆ ts        ┆ ets      │
│           ┆           ┆           ┆           ┆   ┆ O-methylt ┆ a         ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ ransf…    ┆           ┆           ┆          │
│ ENSG00000 ┆ EFO_00057 ┆ disease_p ┆ expressio ┆ … ┆ dehydroge ┆ neurodege ┆ opentarge ┆ opentarg │
│ 292338    ┆ 72        ┆ rotein_po ┆ n upregul ┆   ┆ nase/redu ┆ nerative  ┆ ts        ┆ ets      │
│           ┆           ┆ sitive    ┆ ated      ┆   ┆ ctase     ┆ disease   ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ X-link…   ┆           ┆           ┆          │
│ ENSG00000 ┆ EFO_00005 ┆ disease_p ┆ associate ┆ … ┆ vesicle   ┆ glioblast ┆ opentarge ┆ opentarg │
│ 292366    ┆ 19        ┆ rotein    ┆ d with    ┆   ┆ associate ┆ oma multi ┆ ts        ┆ ets      │
│           ┆           ┆           ┆           ┆   ┆ d         ┆ forme     ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ membrane  ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ pr…       ┆           ┆           ┆          │
│ ENSG00000 ┆ EFO_00005 ┆ disease_p ┆ associate ┆ … ┆ vesicle   ┆ lung aden ┆ opentarge ┆ opentarg │
│ 292366    ┆ 71        ┆ rotein    ┆ d with    ┆   ┆ associate ┆ ocarcinom ┆ ts        ┆ ets      │
│           ┆           ┆           ┆           ┆   ┆ d         ┆ a         ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ membrane  ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ pr…       ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘