In [8]:
import polars as pl

In [58]:
ctd_exposure_protein_interactions = catalog.load(
    "silver.ctd.ctd_exposure_protein_interactions"
)

[06/26/25 01:43:08] INFO     Loading data from                                            ]8;id=604131;file:///home/viti/Documents/repos/personal/hardvard/optimuskg/.venv/lib/python3.12/site-packages/kedro/io/kedro_data_catalog.py\kedro_data_catalog.py]8;;\:]8;id=692177;file:///home/viti/Documents/repos/personal/hardvard/optimuskg/.venv/lib/python3.12/site-packages/kedro/io/kedro_data_catalog.py#757\757]8;;\
                             silver.ctd.ctd_exposure_protein_interactions (CSVDataset)...

In [59]:
ctd_exposure_protein_interactions

shape: (0, 10)
┌──────────┬───────────────┬──────┬────────┬───┬──────┬────────┬────────┬──────────┐
│ relation ┆ relation_type ┆ x_id ┆ x_type ┆ … ┆ y_id ┆ y_type ┆ y_name ┆ y_source │
│ ---      ┆ ---           ┆ ---  ┆ ---    ┆   ┆ ---  ┆ ---    ┆ ---    ┆ ---      │
│ str      ┆ str           ┆ str  ┆ str    ┆   ┆ str  ┆ str    ┆ str    ┆ str      │
╞══════════╪═══════════════╪══════╪════════╪═══╪══════╪════════╪════════╪══════════╡
└──────────┴───────────────┴──────┴────────┴───┴──────┴────────┴────────┴──────────┘

In [45]:
disease_phenotype = (
    hpo_mappings.filter(
        pl.col("database_id").str.contains(
            "Orphanet_"
        )  # NOTE: Only keep diseases from the phenotype mappings
    )
    .with_columns(
        pl.when(pl.col("qualifier").is_null())
        .then(pl.lit("phenotype_present"))
        .otherwise(pl.lit("phenotype_absent"))
        .alias("relation_type"),
        pl.col("database_id").alias("disease_id"),
    )
    .drop(["qualifier", "database_id"])
)
disease_phenotype

shape: (114_960, 4)
┌───────────────────┬────────────┬───────────────────┬────────────────┐
│ disease_name      ┆ hpo_id     ┆ relation_type     ┆ disease_id     │
│ ---               ┆ ---        ┆ ---               ┆ ---            │
│ str               ┆ str        ┆ str               ┆ str            │
╞═══════════════════╪════════════╪═══════════════════╪════════════════╡
│ Woolly hair nevus ┆ HP_0002212 ┆ phenotype_present ┆ Orphanet_79414 │
│ Woolly hair nevus ┆ HP_0002213 ┆ phenotype_present ┆ Orphanet_79414 │
│ Woolly hair nevus ┆ HP_0011365 ┆ phenotype_present ┆ Orphanet_79414 │
│ Woolly hair nevus ┆ HP_0040149 ┆ phenotype_present ┆ Orphanet_79414 │
│ Woolly hair nevus ┆ HP_0007534 ┆ phenotype_present ┆ Orphanet_79414 │
│ …                 ┆ …          ┆ …                 ┆ …              │
│ Temtamy syndrome  ┆ HP_0000324 ┆ phenotype_present ┆ Orphanet_1777  │
│ Temtamy syndrome  ┆ HP_0000506 ┆ phenotype_present ┆ Orphanet_1777  │
│ Temtamy syndrome  ┆ HP_0000568 ┆ phenotype_present ┆ Orphanet_1777  │
│ Temtamy syndrome  ┆ HP_0004209 ┆ phenotype_present ┆ Orphanet_1777  │
│ Temtamy syndrome  ┆ HP_0001382 ┆ phenotype_present ┆ Orphanet_1777  │
└───────────────────┴────────────┴───────────────────┴────────────────┘

In [39]:
mondo_xrefs

shape: (134_206, 2)
┌───────────────┬─────────────────┐
│ id            ┆ xref_id         │
│ ---           ┆ ---             │
│ str           ┆ str             │
╞═══════════════╪═════════════════╡
│ MONDO_0000728 ┆ MESH:D001763    │
│ MONDO_0018380 ┆ Orphanet_399307 │
│ MONDO_0006451 ┆ MedDRA:10061031 │
│ MONDO_0010011 ┆ SCTID:253159001 │
│ MONDO_0001470 ┆ ICD9:173.5      │
│ …             ┆ …               │
│ MONDO_0024386 ┆ UMLS:C1707407   │
│ MONDO_0060486 ┆ DOID:0080978    │
│ MONDO_0006226 ┆ NCIT:C5266      │
│ MONDO_0009001 ┆ Orphanet_91494  │
│ MONDO_0012513 ┆ SCTID:609574004 │
└───────────────┴─────────────────┘

In [46]:
disease_phenotype = disease_phenotype.join(
    mondo_xrefs,
    left_on="disease_id",
    right_on="xref_id",
    how="left",
)
disease_phenotype

shape: (114_960, 5)
┌───────────────────┬────────────┬───────────────────┬────────────────┬───────────────┐
│ disease_name      ┆ hpo_id     ┆ relation_type     ┆ disease_id     ┆ id            │
│ ---               ┆ ---        ┆ ---               ┆ ---            ┆ ---           │
│ str               ┆ str        ┆ str               ┆ str            ┆ str           │
╞═══════════════════╪════════════╪═══════════════════╪════════════════╪═══════════════╡
│ Woolly hair nevus ┆ HP_0002212 ┆ phenotype_present ┆ Orphanet_79414 ┆ MONDO_0019311 │
│ Woolly hair nevus ┆ HP_0002213 ┆ phenotype_present ┆ Orphanet_79414 ┆ MONDO_0019311 │
│ Woolly hair nevus ┆ HP_0011365 ┆ phenotype_present ┆ Orphanet_79414 ┆ MONDO_0019311 │
│ Woolly hair nevus ┆ HP_0040149 ┆ phenotype_present ┆ Orphanet_79414 ┆ MONDO_0019311 │
│ Woolly hair nevus ┆ HP_0007534 ┆ phenotype_present ┆ Orphanet_79414 ┆ MONDO_0019311 │
│ …                 ┆ …          ┆ …                 ┆ …              ┆ …             │
│ Temtamy syndrome  ┆ HP_0000324 ┆ phenotype_present ┆ Orphanet_1777  ┆ MONDO_0009033 │
│ Temtamy syndrome  ┆ HP_0000506 ┆ phenotype_present ┆ Orphanet_1777  ┆ MONDO_0009033 │
│ Temtamy syndrome  ┆ HP_0000568 ┆ phenotype_present ┆ Orphanet_1777  ┆ MONDO_0009033 │
│ Temtamy syndrome  ┆ HP_0004209 ┆ phenotype_present ┆ Orphanet_1777  ┆ MONDO_0009033 │
│ Temtamy syndrome  ┆ HP_0001382 ┆ phenotype_present ┆ Orphanet_1777  ┆ MONDO_0009033 │
└───────────────────┴────────────┴───────────────────┴────────────────┴───────────────┘

In [47]:
disease_phenotype = disease_phenotype.join(
    phenotypes,
    left_on="hpo_id",
    right_on="id",
    how="left",
)
disease_phenotype

shape: (114_960, 7)
┌───────────────┬────────────┬───────────────┬──────────────┬──────────────┬──────────────┬────────┐
│ disease_name  ┆ hpo_id     ┆ relation_type ┆ disease_id   ┆ id           ┆ name         ┆ source │
│ ---           ┆ ---        ┆ ---           ┆ ---          ┆ ---          ┆ ---          ┆ ---    │
│ str           ┆ str        ┆ str           ┆ str          ┆ str          ┆ str          ┆ str    │
╞═══════════════╪════════════╪═══════════════╪══════════════╪══════════════╪══════════════╪════════╡
│ Woolly hair   ┆ HP_0002212 ┆ phenotype_pre ┆ Orphanet_794 ┆ MONDO_001931 ┆ Curly hair   ┆ HPO    │
│ nevus         ┆            ┆ sent          ┆ 14           ┆ 1            ┆              ┆        │
│ Woolly hair   ┆ HP_0002213 ┆ phenotype_pre ┆ Orphanet_794 ┆ MONDO_001931 ┆ Fine hair    ┆ HPO    │
│ nevus         ┆            ┆ sent          ┆ 14           ┆ 1            ┆              ┆        │
│ Woolly hair   ┆ HP_0011365 ┆ phenotype_pre ┆ Orphanet_794 ┆ MONDO_001931 ┆ Patchy hypop ┆ HPO    │
│ nevus         ┆            ┆ sent          ┆ 14           ┆ 1            ┆ igmentation  ┆        │
│               ┆            ┆               ┆              ┆              ┆ of hai…      ┆        │
│ Woolly hair   ┆ HP_0040149 ┆ phenotype_pre ┆ Orphanet_794 ┆ MONDO_001931 ┆ Woolly scalp ┆ HPO    │
│ nevus         ┆            ┆ sent          ┆ 14           ┆ 1            ┆ hair         ┆        │
│ Woolly hair   ┆ HP_0007534 ┆ phenotype_pre ┆ Orphanet_794 ┆ MONDO_001931 ┆ Congenital   ┆ HPO    │
│ nevus         ┆            ┆ sent          ┆ 14           ┆ 1            ┆ posterior    ┆        │
│               ┆            ┆               ┆              ┆              ┆ occipital…   ┆        │
│ …             ┆ …          ┆ …             ┆ …            ┆ …            ┆ …            ┆ …      │
│ Temtamy       ┆ HP_0000324 ┆ phenotype_pre ┆ Orphanet_177 ┆ MONDO_000903 ┆ Facial       ┆ HPO    │
│ syndrome      ┆            ┆ sent          ┆ 7            ┆ 3            ┆ asymmetry    ┆        │
│ Temtamy       ┆ HP_0000506 ┆ phenotype_pre ┆ Orphanet_177 ┆ MONDO_000903 ┆ Telecanthus  ┆ HPO    │
│ syndrome      ┆            ┆ sent          ┆ 7            ┆ 3            ┆              ┆        │
│ Temtamy       ┆ HP_0000568 ┆ phenotype_pre ┆ Orphanet_177 ┆ MONDO_000903 ┆ Microphthalm ┆ HPO    │
│ syndrome      ┆            ┆ sent          ┆ 7            ┆ 3            ┆ ia           ┆        │
│ Temtamy       ┆ HP_0004209 ┆ phenotype_pre ┆ Orphanet_177 ┆ MONDO_000903 ┆ Clinodactyly ┆ HPO    │
│ syndrome      ┆            ┆ sent          ┆ 7            ┆ 3            ┆ of the 5th   ┆        │
│               ┆            ┆               ┆              ┆              ┆ finger       ┆        │
│ Temtamy       ┆ HP_0001382 ┆ phenotype_pre ┆ Orphanet_177 ┆ MONDO_000903 ┆ Joint hyperm ┆ HPO    │
│ syndrome      ┆            ┆ sent          ┆ 7            ┆ 3            ┆ obility      ┆        │
└───────────────┴────────────┴───────────────┴──────────────┴──────────────┴──────────────┴────────┘

In [48]:
disease_phenotype = disease_phenotype.join(
    mondo_terms,
    left_on="id",
    right_on="id",
    how="left",
)
disease_phenotype

shape: (114_960, 9)
┌────────────┬────────────┬────────────┬────────────┬───┬────────────┬────────┬────────────┬───────┐
│ disease_na ┆ hpo_id     ┆ relation_t ┆ disease_id ┆ … ┆ name       ┆ source ┆ name_right ┆ type  │
│ me         ┆ ---        ┆ ype        ┆ ---        ┆   ┆ ---        ┆ ---    ┆ ---        ┆ ---   │
│ ---        ┆ str        ┆ ---        ┆ str        ┆   ┆ str        ┆ str    ┆ str        ┆ str   │
│ str        ┆            ┆ str        ┆            ┆   ┆            ┆        ┆            ┆       │
╞════════════╪════════════╪════════════╪════════════╪═══╪════════════╪════════╪════════════╪═══════╡
│ Woolly     ┆ HP_0002212 ┆ phenotype_ ┆ Orphanet_7 ┆ … ┆ Curly hair ┆ HPO    ┆ wooly hair ┆ CLASS │
│ hair nevus ┆            ┆ present    ┆ 9414       ┆   ┆            ┆        ┆ nevus      ┆       │
│ Woolly     ┆ HP_0002213 ┆ phenotype_ ┆ Orphanet_7 ┆ … ┆ Fine hair  ┆ HPO    ┆ wooly hair ┆ CLASS │
│ hair nevus ┆            ┆ present    ┆ 9414       ┆   ┆            ┆        ┆ nevus      ┆       │
│ Woolly     ┆ HP_0011365 ┆ phenotype_ ┆ Orphanet_7 ┆ … ┆ Patchy hyp ┆ HPO    ┆ wooly hair ┆ CLASS │
│ hair nevus ┆            ┆ present    ┆ 9414       ┆   ┆ opigmentat ┆        ┆ nevus      ┆       │
│            ┆            ┆            ┆            ┆   ┆ ion of     ┆        ┆            ┆       │
│            ┆            ┆            ┆            ┆   ┆ hai…       ┆        ┆            ┆       │
│ Woolly     ┆ HP_0040149 ┆ phenotype_ ┆ Orphanet_7 ┆ … ┆ Woolly     ┆ HPO    ┆ wooly hair ┆ CLASS │
│ hair nevus ┆            ┆ present    ┆ 9414       ┆   ┆ scalp hair ┆        ┆ nevus      ┆       │
│ Woolly     ┆ HP_0007534 ┆ phenotype_ ┆ Orphanet_7 ┆ … ┆ Congenital ┆ HPO    ┆ wooly hair ┆ CLASS │
│ hair nevus ┆            ┆ present    ┆ 9414       ┆   ┆ posterior  ┆        ┆ nevus      ┆       │
│            ┆            ┆            ┆            ┆   ┆ occipital… ┆        ┆            ┆       │
│ …          ┆ …          ┆ …          ┆ …          ┆ … ┆ …          ┆ …      ┆ …          ┆ …     │
│ Temtamy    ┆ HP_0000324 ┆ phenotype_ ┆ Orphanet_1 ┆ … ┆ Facial     ┆ HPO    ┆ temtamy    ┆ CLASS │
│ syndrome   ┆            ┆ present    ┆ 777        ┆   ┆ asymmetry  ┆        ┆ syndrome   ┆       │
│ Temtamy    ┆ HP_0000506 ┆ phenotype_ ┆ Orphanet_1 ┆ … ┆ Telecanthu ┆ HPO    ┆ temtamy    ┆ CLASS │
│ syndrome   ┆            ┆ present    ┆ 777        ┆   ┆ s          ┆        ┆ syndrome   ┆       │
│ Temtamy    ┆ HP_0000568 ┆ phenotype_ ┆ Orphanet_1 ┆ … ┆ Microphtha ┆ HPO    ┆ temtamy    ┆ CLASS │
│ syndrome   ┆            ┆ present    ┆ 777        ┆   ┆ lmia       ┆        ┆ syndrome   ┆       │
│ Temtamy    ┆ HP_0004209 ┆ phenotype_ ┆ Orphanet_1 ┆ … ┆ Clinodacty ┆ HPO    ┆ temtamy    ┆ CLASS │
│ syndrome   ┆            ┆ present    ┆ 777        ┆   ┆ ly of the  ┆        ┆ syndrome   ┆       │
│            ┆            ┆            ┆            ┆   ┆ 5th finger ┆        ┆            ┆       │
│ Temtamy    ┆ HP_0001382 ┆ phenotype_ ┆ Orphanet_1 ┆ … ┆ Joint hype ┆ HPO    ┆ temtamy    ┆ CLASS │
│ syndrome   ┆            ┆ present    ┆ 777        ┆   ┆ rmobility  ┆        ┆ syndrome   ┆       │
└────────────┴────────────┴────────────┴────────────┴───┴────────────┴────────┴────────────┴───────┘

In [50]:
disease_phenotype.rename(
    {"id": "x_id", "disease_name": "x_name", "hpo_id": "y_id", "name": "y_name"}
)

shape: (114_960, 9)
┌────────────┬────────────┬────────────┬────────────┬───┬────────────┬────────┬────────────┬───────┐
│ x_name     ┆ y_id       ┆ relation_t ┆ disease_id ┆ … ┆ y_name     ┆ source ┆ name_right ┆ type  │
│ ---        ┆ ---        ┆ ype        ┆ ---        ┆   ┆ ---        ┆ ---    ┆ ---        ┆ ---   │
│ str        ┆ str        ┆ ---        ┆ str        ┆   ┆ str        ┆ str    ┆ str        ┆ str   │
│            ┆            ┆ str        ┆            ┆   ┆            ┆        ┆            ┆       │
╞════════════╪════════════╪════════════╪════════════╪═══╪════════════╪════════╪════════════╪═══════╡
│ Woolly     ┆ HP_0002212 ┆ phenotype_ ┆ Orphanet_7 ┆ … ┆ Curly hair ┆ HPO    ┆ wooly hair ┆ CLASS │
│ hair nevus ┆            ┆ present    ┆ 9414       ┆   ┆            ┆        ┆ nevus      ┆       │
│ Woolly     ┆ HP_0002213 ┆ phenotype_ ┆ Orphanet_7 ┆ … ┆ Fine hair  ┆ HPO    ┆ wooly hair ┆ CLASS │
│ hair nevus ┆            ┆ present    ┆ 9414       ┆   ┆            ┆        ┆ nevus      ┆       │
│ Woolly     ┆ HP_0011365 ┆ phenotype_ ┆ Orphanet_7 ┆ … ┆ Patchy hyp ┆ HPO    ┆ wooly hair ┆ CLASS │
│ hair nevus ┆            ┆ present    ┆ 9414       ┆   ┆ opigmentat ┆        ┆ nevus      ┆       │
│            ┆            ┆            ┆            ┆   ┆ ion of     ┆        ┆            ┆       │
│            ┆            ┆            ┆            ┆   ┆ hai…       ┆        ┆            ┆       │
│ Woolly     ┆ HP_0040149 ┆ phenotype_ ┆ Orphanet_7 ┆ … ┆ Woolly     ┆ HPO    ┆ wooly hair ┆ CLASS │
│ hair nevus ┆            ┆ present    ┆ 9414       ┆   ┆ scalp hair ┆        ┆ nevus      ┆       │
│ Woolly     ┆ HP_0007534 ┆ phenotype_ ┆ Orphanet_7 ┆ … ┆ Congenital ┆ HPO    ┆ wooly hair ┆ CLASS │
│ hair nevus ┆            ┆ present    ┆ 9414       ┆   ┆ posterior  ┆        ┆ nevus      ┆       │
│            ┆            ┆            ┆            ┆   ┆ occipital… ┆        ┆            ┆       │
│ …          ┆ …          ┆ …          ┆ …          ┆ … ┆ …          ┆ …      ┆ …          ┆ …     │
│ Temtamy    ┆ HP_0000324 ┆ phenotype_ ┆ Orphanet_1 ┆ … ┆ Facial     ┆ HPO    ┆ temtamy    ┆ CLASS │
│ syndrome   ┆            ┆ present    ┆ 777        ┆   ┆ asymmetry  ┆        ┆ syndrome   ┆       │
│ Temtamy    ┆ HP_0000506 ┆ phenotype_ ┆ Orphanet_1 ┆ … ┆ Telecanthu ┆ HPO    ┆ temtamy    ┆ CLASS │
│ syndrome   ┆            ┆ present    ┆ 777        ┆   ┆ s          ┆        ┆ syndrome   ┆       │
│ Temtamy    ┆ HP_0000568 ┆ phenotype_ ┆ Orphanet_1 ┆ … ┆ Microphtha ┆ HPO    ┆ temtamy    ┆ CLASS │
│ syndrome   ┆            ┆ present    ┆ 777        ┆   ┆ lmia       ┆        ┆ syndrome   ┆       │
│ Temtamy    ┆ HP_0004209 ┆ phenotype_ ┆ Orphanet_1 ┆ … ┆ Clinodacty ┆ HPO    ┆ temtamy    ┆ CLASS │
│ syndrome   ┆            ┆ present    ┆ 777        ┆   ┆ ly of the  ┆        ┆ syndrome   ┆       │
│            ┆            ┆            ┆            ┆   ┆ 5th finger ┆        ┆            ┆       │
│ Temtamy    ┆ HP_0001382 ┆ phenotype_ ┆ Orphanet_1 ┆ … ┆ Joint hype ┆ HPO    ┆ temtamy    ┆ CLASS │
│ syndrome   ┆            ┆ present    ┆ 777        ┆   ┆ rmobility  ┆        ┆ syndrome   ┆       │
└────────────┴────────────┴────────────┴────────────┴───┴────────────┴────────┴────────────┴───────┘

In [57]:
silver_disease_phenotype

shape: (114_960, 10)
┌────────────┬────────────┬───────────┬─────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ relation   ┆ relation_t ┆ x_id      ┆ x_type  ┆ … ┆ y_id      ┆ y_type    ┆ y_name    ┆ y_source │
│ ---        ┆ ype        ┆ ---       ┆ ---     ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ str        ┆ ---        ┆ str       ┆ str     ┆   ┆ str       ┆ str       ┆ str       ┆ str      │
│            ┆ str        ┆           ┆         ┆   ┆           ┆           ┆           ┆          │
╞════════════╪════════════╪═══════════╪═════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ disease_ph ┆ phenotype_ ┆ MONDO_001 ┆ disease ┆ … ┆ HP_000221 ┆ phenotype ┆ Curly     ┆ HPO      │
│ enotype    ┆ present    ┆ 9311      ┆         ┆   ┆ 2         ┆           ┆ hair      ┆          │
│ disease_ph ┆ phenotype_ ┆ MONDO_001 ┆ disease ┆ … ┆ HP_000221 ┆ phenotype ┆ Fine hair ┆ HPO      │
│ enotype    ┆ present    ┆ 9311      ┆         ┆   ┆ 3         ┆           ┆           ┆          │
│ disease_ph ┆ phenotype_ ┆ MONDO_001 ┆ disease ┆ … ┆ HP_001136 ┆ phenotype ┆ Patchy    ┆ HPO      │
│ enotype    ┆ present    ┆ 9311      ┆         ┆   ┆ 5         ┆           ┆ hypopigme ┆          │
│            ┆            ┆           ┆         ┆   ┆           ┆           ┆ ntation   ┆          │
│            ┆            ┆           ┆         ┆   ┆           ┆           ┆ of hai…   ┆          │
│ disease_ph ┆ phenotype_ ┆ MONDO_001 ┆ disease ┆ … ┆ HP_004014 ┆ phenotype ┆ Woolly    ┆ HPO      │
│ enotype    ┆ present    ┆ 9311      ┆         ┆   ┆ 9         ┆           ┆ scalp     ┆          │
│            ┆            ┆           ┆         ┆   ┆           ┆           ┆ hair      ┆          │
│ disease_ph ┆ phenotype_ ┆ MONDO_001 ┆ disease ┆ … ┆ HP_000753 ┆ phenotype ┆ Congenita ┆ HPO      │
│ enotype    ┆ present    ┆ 9311      ┆         ┆   ┆ 4         ┆           ┆ l         ┆          │
│            ┆            ┆           ┆         ┆   ┆           ┆           ┆ posterior ┆          │
│            ┆            ┆           ┆         ┆   ┆           ┆           ┆ occipital ┆          │
│            ┆            ┆           ┆         ┆   ┆           ┆           ┆ …         ┆          │
│ …          ┆ …          ┆ …         ┆ …       ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ disease_ph ┆ phenotype_ ┆ MONDO_000 ┆ disease ┆ … ┆ HP_000032 ┆ phenotype ┆ Facial    ┆ HPO      │
│ enotype    ┆ present    ┆ 9033      ┆         ┆   ┆ 4         ┆           ┆ asymmetry ┆          │
│ disease_ph ┆ phenotype_ ┆ MONDO_000 ┆ disease ┆ … ┆ HP_000050 ┆ phenotype ┆ Telecanth ┆ HPO      │
│ enotype    ┆ present    ┆ 9033      ┆         ┆   ┆ 6         ┆           ┆ us        ┆          │
│ disease_ph ┆ phenotype_ ┆ MONDO_000 ┆ disease ┆ … ┆ HP_000056 ┆ phenotype ┆ Microphth ┆ HPO      │
│ enotype    ┆ present    ┆ 9033      ┆         ┆   ┆ 8         ┆           ┆ almia     ┆          │
│ disease_ph ┆ phenotype_ ┆ MONDO_000 ┆ disease ┆ … ┆ HP_000420 ┆ phenotype ┆ Clinodact ┆ HPO      │
│ enotype    ┆ present    ┆ 9033      ┆         ┆   ┆ 9         ┆           ┆ yly of    ┆          │
│            ┆            ┆           ┆         ┆   ┆           ┆           ┆ the 5th   ┆          │
│            ┆            ┆           ┆         ┆   ┆           ┆           ┆ finger    ┆          │
│ disease_ph ┆ phenotype_ ┆ MONDO_000 ┆ disease ┆ … ┆ HP_000138 ┆ phenotype ┆ Joint hyp ┆ HPO      │
│ enotype    ┆ present    ┆ 9033      ┆         ┆   ┆ 2         ┆           ┆ ermobilit ┆          │
│            ┆            ┆           ┆         ┆   ┆           ┆           ┆ y         ┆          │
└────────────┴────────────┴───────────┴─────────┴───┴───────────┴───────────┴───────────┴──────────┘