In [113]:
import re
import polars as pl

In [116]:
ctd_exposure_events = catalog.load("bronze.ctd.ctd_exposure_events")
go_terms = catalog.load("bronze.ontology.go_terms")

[06/11/25 23:53:53] INFO     Loading data from bronze.ctd.ctd_exposure_events             ]8;id=814019;file:///home/viti/Documents/repos/personal/hardvard/optimuskg/.venv/lib/python3.12/site-packages/kedro/io/kedro_data_catalog.py\kedro_data_catalog.py]8;;\:]8;id=372111;file:///home/viti/Documents/repos/personal/hardvard/optimuskg/.venv/lib/python3.12/site-packages/kedro/io/kedro_data_catalog.py#757\757]8;;\
                             (CSVDataset)...

                    INFO     Loading data from bronze.ontology.go_terms (CSVDataset)...   ]8;id=979560;file:///home/viti/Documents/repos/personal/hardvard/optimuskg/.venv/lib/python3.12/site-packages/kedro/io/kedro_data_catalog.py\kedro_data_catalog.py]8;;\:]8;id=148169;file:///home/viti/Documents/repos/personal/hardvard/optimuskg/.venv/lib/python3.12/site-packages/kedro/io/kedro_data_catalog.py#757\757]8;;\

In [120]:
go_terms.head()

shape: (5, 3)
┌────────────┬─────────────────────────────────┬───────┐
│ id         ┆ name                            ┆ type  │
│ ---        ┆ ---                             ┆ ---   │
│ str        ┆ str                             ┆ str   │
╞════════════╪═════════════════════════════════╪═══════╡
│ GO_1903199 ┆ obsolete negative regulation o… ┆ CLASS │
│ GO_0032404 ┆ mismatch repair complex bindin… ┆ CLASS │
│ GO_0016534 ┆ null                            ┆ CLASS │
│ GO_0045762 ┆ positive regulation of adenyla… ┆ CLASS │
│ GO_0102919 ┆ 5,6-dimethylbenzimidazole synt… ┆ CLASS │
└────────────┴─────────────────────────────────┴───────┘

In [121]:
ctd_exposure_events.head()

shape: (5, 43)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ exposure_ ┆ exposure_ ┆ stressor_ ┆ stressor_ ┆ … ┆ associate ┆ enrollmen ┆ enrollmen ┆ study_fa │
│ stressor_ ┆ stressor_ ┆ source_ca ┆ source_de ┆   ┆ d_study_t ┆ t_start_y ┆ t_end_yea ┆ ctors    │
│ name      ┆ id        ┆ tegory    ┆ tails     ┆   ┆ itles     ┆ ear       ┆ r         ┆ ---      │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ str      │
│ str       ┆ str       ┆ str       ┆ str       ┆   ┆ str       ┆ str       ┆ str       ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 1,1,1-tri ┆ MESH:C024 ┆ Commercia ┆ null      ┆ … ┆ The       ┆ 2001      ┆ 2001      ┆ null     │
│ chloroeth ┆ 566       ┆ l product ┆           ┆   ┆ School    ┆           ┆           ┆          │
│ ane       ┆           ┆ |Dietary| ┆           ┆   ┆ Health    ┆           ┆           ┆          │
│           ┆           ┆ Env…      ┆           ┆   ┆ Initiativ ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ e: …      ┆           ┆           ┆          │
│ 1,1,1-tri ┆ MESH:C024 ┆ Commercia ┆ null      ┆ … ┆ The       ┆ 2001      ┆ 2001      ┆ null     │
│ chloroeth ┆ 566       ┆ l product ┆           ┆   ┆ School    ┆           ┆           ┆          │
│ ane       ┆           ┆ |Dietary| ┆           ┆   ┆ Health    ┆           ┆           ┆          │
│           ┆           ┆ Env…      ┆           ┆   ┆ Initiativ ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ e: …      ┆           ┆           ┆          │
│ 1,1,1-tri ┆ MESH:C024 ┆ Commercia ┆ null      ┆ … ┆ The       ┆ 2001      ┆ 2001      ┆ null     │
│ chloroeth ┆ 566       ┆ l product ┆           ┆   ┆ School    ┆           ┆           ┆          │
│ ane       ┆           ┆ |Dietary| ┆           ┆   ┆ Health    ┆           ┆           ┆          │
│           ┆           ┆ Env…      ┆           ┆   ┆ Initiativ ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ e: …      ┆           ┆           ┆          │
│ 1,1,1-tri ┆ MESH:C024 ┆ Commercia ┆ null      ┆ … ┆ The       ┆ 2001      ┆ 2001      ┆ null     │
│ chloroeth ┆ 566       ┆ l product ┆           ┆   ┆ School    ┆           ┆           ┆          │
│ ane       ┆           ┆ |Dietary| ┆           ┆   ┆ Health    ┆           ┆           ┆          │
│           ┆           ┆ Env…      ┆           ┆   ┆ Initiativ ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ e: …      ┆           ┆           ┆          │
│ 1,1,1-tri ┆ MESH:C024 ┆ Commercia ┆ null      ┆ … ┆ The       ┆ 2001      ┆ 2001      ┆ null     │
│ chloroeth ┆ 566       ┆ l product ┆           ┆   ┆ School    ┆           ┆           ┆          │
│ ane       ┆           ┆ |Dietary| ┆           ┆   ┆ Health    ┆           ┆           ┆          │
│           ┆           ┆ Env…      ┆           ┆   ┆ Initiativ ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ e: …      ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [124]:
df_exp_path = ctd_exposure_events.select(
    ["exposure_stressor_name", "exposure_stressor_id", "phenotype_name", "phenotype_id"]
).filter(pl.col("phenotype_id").is_not_null())
df_exp_path = df_exp_path.with_columns(
    pl.col("phenotype_id").str.replace("GO:", "GO_").alias("phenotype_id")
)
df_exp_path

shape: (4_196, 4)
┌──────────────────────────────┬──────────────────────┬─────────────────────────────┬──────────────┐
│ exposure_stressor_name       ┆ exposure_stressor_id ┆ phenotype_name              ┆ phenotype_id │
│ ---                          ┆ ---                  ┆ ---                         ┆ ---          │
│ str                          ┆ str                  ┆ str                         ┆ str          │
╞══════════════════════════════╪══════════════════════╪═════════════════════════════╪══════════════╡
│ 1,12-benzoperylene           ┆ MESH:C006718         ┆ cholesterol homeostasis     ┆ GO_0042632   │
│ 1,2,3,4,6,7,8-heptachlorodib ┆ MESH:C046839         ┆ regulation of blood         ┆ GO_0008217   │
│ en…                          ┆                      ┆ pressure                    ┆              │
│ 1,2,3,4,6,7,8-heptachlorodib ┆ MESH:C473650         ┆ regulation of blood         ┆ GO_0008217   │
│ en…                          ┆                      ┆ pressure                    ┆              │
│ 1,2,3,4,6,7,8-heptachlorodib ┆ MESH:C473650         ┆ triglyceride metabolic      ┆ GO_0006641   │
│ en…                          ┆                      ┆ process                     ┆              │
│ 1,2,3,4,7,8-hexachlorodibenz ┆ MESH:C051412         ┆ regulation of blood         ┆ GO_0008217   │
│ of…                          ┆                      ┆ pressure                    ┆              │
│ …                            ┆ …                    ┆ …                           ┆ …            │
│ Zinc                         ┆ MESH:D015032         ┆ glucose homeostasis         ┆ GO_0042593   │
│ Zinc                         ┆ MESH:D015032         ┆ glucose homeostasis         ┆ GO_0042593   │
│ Zinc                         ┆ MESH:D015032         ┆ glucose metabolic process   ┆ GO_0006006   │
│ Zinc                         ┆ MESH:D015032         ┆ inflammatory response       ┆ GO_0006954   │
│ Zinc                         ┆ MESH:D015032         ┆ inflammatory response       ┆ GO_0006954   │
└──────────────────────────────┴──────────────────────┴─────────────────────────────┴──────────────┘

In [130]:
df_exp_path = df_exp_path.join(
    go_terms, left_on="phenotype_id", right_on="id", how="inner"
)
df_exp_path

╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ in <module>:1                                                                                    │
│                                                                                                  │
│ ❱ 1 df_exp_path = df_exp_path.join(go_terms.select(["id", "name"]), left_on="phenotype_id",      │
│   2 df_exp_path                                                                                  │
│   3                                                                                              │
│                                                                                                  │
│ /home/viti/Documents/repos/personal/hardvard/optimuskg/.venv/lib/python3.12/site-packages/polars │
│ /_utils/deprecation.py:119 in wrapper                                                            │
│                                                                                                  │
│   116 │   │   │   _rename_keyword_argument(                                                      │
│   117 │   │   │   │   old_name, new_name, kwargs, function.__qualname__, version                 │
│   118 │   │   │   )                                                                              │
│ ❱ 119 │   │   │   return function(*args, **kwargs)                                               │
│   120 │   │                                                                                      │
│   121 │   │   wrapper.__signature__ = inspect.signature(function)  # type: ignore[attr-defined   │
│   122 │   │   return wrapper                                                                     │
│                                                                                                  │
│ /home/viti/Documents/repos/personal/hardvard/optimuskg/.venv/lib/python3.12/site-packages/polars │
│ /dataframe/frame.py:7765 in join                                                                 │
│                                                                                                  │
│    7762 │   │   │   │   coalesce=coalesce,                                                       │
│    7763 │   │   │   │   maintain_order=maintain_order,                                           │
│    7764 │   │   │   )                                                                            │
│ ❱  7765 │   │   │   .collect(_eager=True)                                                        │
│    7766 │   │   )                                                                                │
│    7767 │                                                                                        │
│    7768 │   @unstable()                                                                          │
│                                                                                                  │
│ /home/viti/Documents/repos/personal/hardvard/optimuskg/.venv/lib/python3.12/site-packages/polars │
│ /_utils/deprecation.py:93 in wrapper                                                             │
│                                                                                                  │
│    90 │   │   │   │                                                                              │
│    91 │   │   │   │   del kwargs["streaming"]                                                    │
│    92 │   │   │                                                                                  │
│ ❱  93 │   │   │   return function(*args, **kwargs)                                               │
│    94 │   │                                                                                      │
│    95 │   │   wrapper.__signature__ = inspect.signature(function)  # type: ignore[attr-defined   │
│    96 │   │   return wrapper                                                                     │
│                                                                                                  │
│ /home/viti/Documents/repos/personal/hardvard/optimuskg/.venv/lib/python3.12/site-packages/polars │
│ /lazyframe/frame.py:2206 in collect                                                              │
│                                                                                                  │
│   2203 │   │                                                                                     │
│   2204 │   │   # Only for testing purposes                                                       │
│   2205 │   │   callback = _kwargs.get("post_opt_callback", callback)                             │
│ ❱ 2206 │   │   return wrap_df(ldf.collect(engine, callback))                                     │
│   2207 │                                                                                         │
│   2208 │   @overload                                                                             │
│   2209 │   def collect_async(                                                                    │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
ColumnNotFoundError: phenotype_id

Resolved plan until failure:

        ---> FAILED HERE RESOLVING 'sink' <---
DF ["id", "name"]; PROJECT */2 COLUMNS

In [126]:
df_exp_path = df_exp_path.rename(
    {
        "exposure_stressor_id": "x_id",
        "exposure_stressor_name": "x_name",
        "phenotype_id": "y_id",
        "phenotype_name": "y_name",
    }
)
df_exp_path

shape: (4_196, 5)
┌───────────────────────┬──────────────┬───────────────────────┬────────────┬──────────────────────┐
│ x_name                ┆ x_id         ┆ y_name                ┆ y_id       ┆ name                 │
│ ---                   ┆ ---          ┆ ---                   ┆ ---        ┆ ---                  │
│ str                   ┆ str          ┆ str                   ┆ str        ┆ str                  │
╞═══════════════════════╪══════════════╪═══════════════════════╪════════════╪══════════════════════╡
│ Cadmium               ┆ MESH:D002104 ┆ negative regulation   ┆ GO_1901318 ┆ negative regulation  │
│                       ┆              ┆ of flagell…           ┆            ┆ of flagell…          │
│ Cadmium               ┆ MESH:D002104 ┆ negative regulation   ┆ GO_1901318 ┆ negative regulation  │
│                       ┆              ┆ of flagell…           ┆            ┆ of flagell…          │
│ Dibutyl Phthalate     ┆ MESH:D003993 ┆ negative regulation   ┆ GO_1901318 ┆ negative regulation  │
│                       ┆              ┆ of flagell…           ┆            ┆ of flagell…          │
│ Diethylhexyl          ┆ MESH:D004051 ┆ negative regulation   ┆ GO_1901318 ┆ negative regulation  │
│ Phthalate             ┆              ┆ of flagell…           ┆            ┆ of flagell…          │
│ Diethylhexyl          ┆ MESH:D004051 ┆ negative regulation   ┆ GO_1901318 ┆ negative regulation  │
│ Phthalate             ┆              ┆ of flagell…           ┆            ┆ of flagell…          │
│ …                     ┆ …            ┆ …                     ┆ …          ┆ …                    │
│ Tobacco Smoke         ┆ MESH:D014028 ┆ developmental growth  ┆ GO_0048589 ┆ developmental growth │
│ Pollution             ┆              ┆                       ┆            ┆                      │
│ 2,4,5,2',4',5'-hexach ┆ MESH:C014024 ┆ IgA receptor activity ┆ GO_0019766 ┆ IgA receptor         │
│ lorobiphe…            ┆              ┆                       ┆            ┆ activity             │
│ Dichlorodiphenyl      ┆ MESH:D003633 ┆ IgA receptor activity ┆ GO_0019766 ┆ IgA receptor         │
│ Dichloroethyl…        ┆              ┆                       ┆            ┆ activity             │
│ bisphenol A           ┆ MESH:C006780 ┆ lactate dehydrogenase ┆ GO_0004457 ┆ lactate              │
│                       ┆              ┆ activity              ┆            ┆ dehydrogenase        │
│                       ┆              ┆                       ┆            ┆ activity             │
│ Hydrocarbons,         ┆ MESH:D006843 ┆ enzyme activator      ┆ GO_0008047 ┆ enzyme activator     │
│ Chlorinated           ┆              ┆ activity              ┆            ┆ activity             │
└───────────────────────┴──────────────┴───────────────────────┴────────────┴──────────────────────┘

In [127]:
df_exp_path = df_exp_path.with_columns(
    [
        pl.lit("exposure").alias("x_type"),
        pl.lit("CTD").alias("x_source"),
        pl.lit("biological process").alias("y_type"),
        pl.lit("GO").alias("y_source"),
        pl.lit("exposure_biological_process").alias("relation"),
        pl.lit("regulates").alias("relation_type"),
    ]
)
df_exp_path

shape: (4_196, 11)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬──────────┬───────────┬───────────┐
│ x_name    ┆ x_id      ┆ y_name    ┆ y_id      ┆ … ┆ y_type    ┆ y_source ┆ relation  ┆ relation_ │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---      ┆ ---       ┆ type      │
│ str       ┆ str       ┆ str       ┆ str       ┆   ┆ str       ┆ str      ┆ str       ┆ ---       │
│           ┆           ┆           ┆           ┆   ┆           ┆          ┆           ┆ str       │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪══════════╪═══════════╪═══════════╡
│ Cadmium   ┆ MESH:D002 ┆ negative  ┆ GO_190131 ┆ … ┆ biologica ┆ GO       ┆ exposure_ ┆ regulates │
│           ┆ 104       ┆ regulatio ┆ 8         ┆   ┆ l process ┆          ┆ biologica ┆           │
│           ┆           ┆ n of      ┆           ┆   ┆           ┆          ┆ l_process ┆           │
│           ┆           ┆ flagell…  ┆           ┆   ┆           ┆          ┆           ┆           │
│ Cadmium   ┆ MESH:D002 ┆ negative  ┆ GO_190131 ┆ … ┆ biologica ┆ GO       ┆ exposure_ ┆ regulates │
│           ┆ 104       ┆ regulatio ┆ 8         ┆   ┆ l process ┆          ┆ biologica ┆           │
│           ┆           ┆ n of      ┆           ┆   ┆           ┆          ┆ l_process ┆           │
│           ┆           ┆ flagell…  ┆           ┆   ┆           ┆          ┆           ┆           │
│ Dibutyl   ┆ MESH:D003 ┆ negative  ┆ GO_190131 ┆ … ┆ biologica ┆ GO       ┆ exposure_ ┆ regulates │
│ Phthalate ┆ 993       ┆ regulatio ┆ 8         ┆   ┆ l process ┆          ┆ biologica ┆           │
│           ┆           ┆ n of      ┆           ┆   ┆           ┆          ┆ l_process ┆           │
│           ┆           ┆ flagell…  ┆           ┆   ┆           ┆          ┆           ┆           │
│ Diethylhe ┆ MESH:D004 ┆ negative  ┆ GO_190131 ┆ … ┆ biologica ┆ GO       ┆ exposure_ ┆ regulates │
│ xyl       ┆ 051       ┆ regulatio ┆ 8         ┆   ┆ l process ┆          ┆ biologica ┆           │
│ Phthalate ┆           ┆ n of      ┆           ┆   ┆           ┆          ┆ l_process ┆           │
│           ┆           ┆ flagell…  ┆           ┆   ┆           ┆          ┆           ┆           │
│ Diethylhe ┆ MESH:D004 ┆ negative  ┆ GO_190131 ┆ … ┆ biologica ┆ GO       ┆ exposure_ ┆ regulates │
│ xyl       ┆ 051       ┆ regulatio ┆ 8         ┆   ┆ l process ┆          ┆ biologica ┆           │
│ Phthalate ┆           ┆ n of      ┆           ┆   ┆           ┆          ┆ l_process ┆           │
│           ┆           ┆ flagell…  ┆           ┆   ┆           ┆          ┆           ┆           │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …        ┆ …         ┆ …         │
│ Tobacco   ┆ MESH:D014 ┆ developme ┆ GO_004858 ┆ … ┆ biologica ┆ GO       ┆ exposure_ ┆ regulates │
│ Smoke     ┆ 028       ┆ ntal      ┆ 9         ┆   ┆ l process ┆          ┆ biologica ┆           │
│ Pollution ┆           ┆ growth    ┆           ┆   ┆           ┆          ┆ l_process ┆           │
│ 2,4,5,2', ┆ MESH:C014 ┆ IgA       ┆ GO_001976 ┆ … ┆ biologica ┆ GO       ┆ exposure_ ┆ regulates │
│ 4',5'-hex ┆ 024       ┆ receptor  ┆ 6         ┆   ┆ l process ┆          ┆ biologica ┆           │
│ achlorobi ┆           ┆ activity  ┆           ┆   ┆           ┆          ┆ l_process ┆           │
│ phe…      ┆           ┆           ┆           ┆   ┆           ┆          ┆           ┆           │
│ Dichlorod ┆ MESH:D003 ┆ IgA       ┆ GO_001976 ┆ … ┆ biologica ┆ GO       ┆ exposure_ ┆ regulates │
│ iphenyl   ┆ 633       ┆ receptor  ┆ 6         ┆   ┆ l process ┆          ┆ biologica ┆           │
│ Dichloroe ┆           ┆ activity  ┆           ┆   ┆           ┆          ┆ l_process ┆           │
│ thyl…     ┆           ┆           ┆           ┆   ┆           ┆          ┆           ┆           │
│ bisphenol ┆ MESH:C006 ┆ lactate   ┆ GO_000445 ┆ … ┆ biologica ┆ GO       ┆ exposure_ ┆ regulates │
│ A         ┆ 780       ┆ dehydroge ┆ 7         ┆   ┆ l process ┆          ┆ biologica ┆           │
│           ┆           ┆ nase      ┆           ┆   ┆           ┆          ┆ l_process ┆           │
│           ┆           ┆ activity  ┆           ┆   ┆           ┆          ┆           ┆           │
│ Hydrocarb ┆ MESH:D006 ┆ enzyme    ┆ GO_000804 ┆ … ┆ biologica ┆ GO       ┆ exposure_ ┆ regulates │
│ ons, Chlo ┆ 843       ┆ activator ┆ 7         ┆   ┆ l process ┆          ┆ biologica ┆           │
│ rinated   ┆           ┆ activity  ┆           ┆   ┆           ┆          ┆ l_process ┆           │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴──────────┴───────────┴───────────┘

In [128]:
df_exp_path = df_exp_path.select(
    [
        "relation",
        "relation_type",
        "x_id",
        "x_type",
        "x_name",
        "x_source",
        "y_id",
        "y_type",
        "y_name",
        "y_source",
    ]
)
df_exp_path

shape: (4_196, 10)
┌────────────┬───────────┬───────────┬──────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ relation   ┆ relation_ ┆ x_id      ┆ x_type   ┆ … ┆ y_id      ┆ y_type    ┆ y_name    ┆ y_source │
│ ---        ┆ type      ┆ ---       ┆ ---      ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ str        ┆ ---       ┆ str       ┆ str      ┆   ┆ str       ┆ str       ┆ str       ┆ str      │
│            ┆ str       ┆           ┆          ┆   ┆           ┆           ┆           ┆          │
╞════════════╪═══════════╪═══════════╪══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ exposure_b ┆ regulates ┆ MESH:D002 ┆ exposure ┆ … ┆ GO_190131 ┆ biologica ┆ negative  ┆ GO       │
│ iological_ ┆           ┆ 104       ┆          ┆   ┆ 8         ┆ l process ┆ regulatio ┆          │
│ process    ┆           ┆           ┆          ┆   ┆           ┆           ┆ n of      ┆          │
│            ┆           ┆           ┆          ┆   ┆           ┆           ┆ flagell…  ┆          │
│ exposure_b ┆ regulates ┆ MESH:D002 ┆ exposure ┆ … ┆ GO_190131 ┆ biologica ┆ negative  ┆ GO       │
│ iological_ ┆           ┆ 104       ┆          ┆   ┆ 8         ┆ l process ┆ regulatio ┆          │
│ process    ┆           ┆           ┆          ┆   ┆           ┆           ┆ n of      ┆          │
│            ┆           ┆           ┆          ┆   ┆           ┆           ┆ flagell…  ┆          │
│ exposure_b ┆ regulates ┆ MESH:D003 ┆ exposure ┆ … ┆ GO_190131 ┆ biologica ┆ negative  ┆ GO       │
│ iological_ ┆           ┆ 993       ┆          ┆   ┆ 8         ┆ l process ┆ regulatio ┆          │
│ process    ┆           ┆           ┆          ┆   ┆           ┆           ┆ n of      ┆          │
│            ┆           ┆           ┆          ┆   ┆           ┆           ┆ flagell…  ┆          │
│ exposure_b ┆ regulates ┆ MESH:D004 ┆ exposure ┆ … ┆ GO_190131 ┆ biologica ┆ negative  ┆ GO       │
│ iological_ ┆           ┆ 051       ┆          ┆   ┆ 8         ┆ l process ┆ regulatio ┆          │
│ process    ┆           ┆           ┆          ┆   ┆           ┆           ┆ n of      ┆          │
│            ┆           ┆           ┆          ┆   ┆           ┆           ┆ flagell…  ┆          │
│ exposure_b ┆ regulates ┆ MESH:D004 ┆ exposure ┆ … ┆ GO_190131 ┆ biologica ┆ negative  ┆ GO       │
│ iological_ ┆           ┆ 051       ┆          ┆   ┆ 8         ┆ l process ┆ regulatio ┆          │
│ process    ┆           ┆           ┆          ┆   ┆           ┆           ┆ n of      ┆          │
│            ┆           ┆           ┆          ┆   ┆           ┆           ┆ flagell…  ┆          │
│ …          ┆ …         ┆ …         ┆ …        ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ exposure_b ┆ regulates ┆ MESH:D014 ┆ exposure ┆ … ┆ GO_004858 ┆ biologica ┆ developme ┆ GO       │
│ iological_ ┆           ┆ 028       ┆          ┆   ┆ 9         ┆ l process ┆ ntal      ┆          │
│ process    ┆           ┆           ┆          ┆   ┆           ┆           ┆ growth    ┆          │
│ exposure_b ┆ regulates ┆ MESH:C014 ┆ exposure ┆ … ┆ GO_001976 ┆ biologica ┆ IgA       ┆ GO       │
│ iological_ ┆           ┆ 024       ┆          ┆   ┆ 6         ┆ l process ┆ receptor  ┆          │
│ process    ┆           ┆           ┆          ┆   ┆           ┆           ┆ activity  ┆          │
│ exposure_b ┆ regulates ┆ MESH:D003 ┆ exposure ┆ … ┆ GO_001976 ┆ biologica ┆ IgA       ┆ GO       │
│ iological_ ┆           ┆ 633       ┆          ┆   ┆ 6         ┆ l process ┆ receptor  ┆          │
│ process    ┆           ┆           ┆          ┆   ┆           ┆           ┆ activity  ┆          │
│ exposure_b ┆ regulates ┆ MESH:C006 ┆ exposure ┆ … ┆ GO_000445 ┆ biologica ┆ lactate   ┆ GO       │
│ iological_ ┆           ┆ 780       ┆          ┆   ┆ 7         ┆ l process ┆ dehydroge ┆          │
│ process    ┆           ┆           ┆          ┆   ┆           ┆           ┆ nase      ┆          │
│            ┆           ┆           ┆          ┆   ┆           ┆           ┆ activity  ┆          │
│ exposure_b ┆ regulates ┆ MESH:D006 ┆ exposure ┆ … ┆ GO_000804 ┆ biologica ┆ enzyme    ┆ GO       │
│ iological_ ┆           ┆ 843       ┆          ┆   ┆ 7         ┆ l process ┆ activator ┆          │
│ process    ┆           ┆           ┆          ┆   ┆           ┆           ┆ activity  ┆          │
└────────────┴───────────┴───────────┴──────────┴───┴───────────┴───────────┴───────────┴──────────┘