In [3]:
import re
import polars as pl

In [89]:
gene_expressions_in_anatomy = catalog.load("silver.bgee.gene_expressions_in_anatomy")
opentargets_edges = catalog.load("silver.opentargets.opentargets_edges")
ctd_exposure_protein_interactions = catalog.load(
    "silver.ctd.ctd_exposure_protein_interactions"
)
ctd_exposure_exposure_interactions = catalog.load(
    "silver.ctd.ctd_exposure_exposure_interactions"
)
drug_drug = catalog.load("silver.drugbank.drug_drug")
drug_protein = catalog.load("silver.drugbank.drug_protein")
protein_biological_process_interactions = catalog.load(
    "silver.ncbigene.protein_biological_process_interactions"
)
protein_cellular_component_interactions = catalog.load(
    "silver.ncbigene.protein_cellular_component_interactions"
)
protein_molecular_function_interactions = catalog.load(
    "silver.ncbigene.protein_molecular_function_interactions"
)
pathway_pathway_interactions = catalog.load(
    "silver.reactome.pathway_pathway_interactions"
)
pathway_protein_interactions = catalog.load(
    "silver.reactome.pathway_protein_interactions"
)

[06/02/25 19:00:59] INFO     Loading data from silver.bgee.gene_expressions_in_anatomy    ]8;id=824334;file:///home/viti/Documents/repos/harvard/optimuskg/.venv/lib/python3.12/site-packages/kedro/io/kedro_data_catalog.py\kedro_data_catalog.py]8;;\:]8;id=301667;file:///home/viti/Documents/repos/harvard/optimuskg/.venv/lib/python3.12/site-packages/kedro/io/kedro_data_catalog.py#757\757]8;;\
                             (CSVDataset)...

                    INFO     Loading data from silver.opentargets.opentargets_edges       ]8;id=970766;file:///home/viti/Documents/repos/harvard/optimuskg/.venv/lib/python3.12/site-packages/kedro/io/kedro_data_catalog.py\kedro_data_catalog.py]8;;\:]8;id=268834;file:///home/viti/Documents/repos/harvard/optimuskg/.venv/lib/python3.12/site-packages/kedro/io/kedro_data_catalog.py#757\757]8;;\
                             (CSVDataset)...

                    INFO     Loading data from                                            ]8;id=119650;file:///home/viti/Documents/repos/harvard/optimuskg/.venv/lib/python3.12/site-packages/kedro/io/kedro_data_catalog.py\kedro_data_catalog.py]8;;\:]8;id=231827;file:///home/viti/Documents/repos/harvard/optimuskg/.venv/lib/python3.12/site-packages/kedro/io/kedro_data_catalog.py#757\757]8;;\
                             silver.ctd.ctd_exposure_protein_interactions (CSVDataset)...

                    INFO     Loading data from                                            ]8;id=676868;file:///home/viti/Documents/repos/harvard/optimuskg/.venv/lib/python3.12/site-packages/kedro/io/kedro_data_catalog.py\kedro_data_catalog.py]8;;\:]8;id=719062;file:///home/viti/Documents/repos/harvard/optimuskg/.venv/lib/python3.12/site-packages/kedro/io/kedro_data_catalog.py#757\757]8;;\
                             silver.ctd.ctd_exposure_exposure_interactions
                             (CSVDataset)...

                    INFO     Loading data from silver.drugbank.drug_drug (CSVDataset)...  ]8;id=172230;file:///home/viti/Documents/repos/harvard/optimuskg/.venv/lib/python3.12/site-packages/kedro/io/kedro_data_catalog.py\kedro_data_catalog.py]8;;\:]8;id=339542;file:///home/viti/Documents/repos/harvard/optimuskg/.venv/lib/python3.12/site-packages/kedro/io/kedro_data_catalog.py#757\757]8;;\

[06/02/25 19:01:00] INFO     Loading data from silver.drugbank.drug_protein               ]8;id=922309;file:///home/viti/Documents/repos/harvard/optimuskg/.venv/lib/python3.12/site-packages/kedro/io/kedro_data_catalog.py\kedro_data_catalog.py]8;;\:]8;id=513860;file:///home/viti/Documents/repos/harvard/optimuskg/.venv/lib/python3.12/site-packages/kedro/io/kedro_data_catalog.py#757\757]8;;\
                             (CSVDataset)...

                    INFO     Loading data from                                            ]8;id=713973;file:///home/viti/Documents/repos/harvard/optimuskg/.venv/lib/python3.12/site-packages/kedro/io/kedro_data_catalog.py\kedro_data_catalog.py]8;;\:]8;id=298484;file:///home/viti/Documents/repos/harvard/optimuskg/.venv/lib/python3.12/site-packages/kedro/io/kedro_data_catalog.py#757\757]8;;\
                             silver.ncbigene.protein_biological_process_interactions
                             (CSVDataset)...

                    INFO     Loading data from                                            ]8;id=532459;file:///home/viti/Documents/repos/harvard/optimuskg/.venv/lib/python3.12/site-packages/kedro/io/kedro_data_catalog.py\kedro_data_catalog.py]8;;\:]8;id=902188;file:///home/viti/Documents/repos/harvard/optimuskg/.venv/lib/python3.12/site-packages/kedro/io/kedro_data_catalog.py#757\757]8;;\
                             silver.ncbigene.protein_cellular_component_interactions
                             (CSVDataset)...

                    INFO     Loading data from                                            ]8;id=577703;file:///home/viti/Documents/repos/harvard/optimuskg/.venv/lib/python3.12/site-packages/kedro/io/kedro_data_catalog.py\kedro_data_catalog.py]8;;\:]8;id=688782;file:///home/viti/Documents/repos/harvard/optimuskg/.venv/lib/python3.12/site-packages/kedro/io/kedro_data_catalog.py#757\757]8;;\
                             silver.ncbigene.protein_molecular_function_interactions
                             (CSVDataset)...

                    INFO     Loading data from                                            ]8;id=39096;file:///home/viti/Documents/repos/harvard/optimuskg/.venv/lib/python3.12/site-packages/kedro/io/kedro_data_catalog.py\kedro_data_catalog.py]8;;\:]8;id=988864;file:///home/viti/Documents/repos/harvard/optimuskg/.venv/lib/python3.12/site-packages/kedro/io/kedro_data_catalog.py#757\757]8;;\
                             silver.reactome.pathway_pathway_interactions (CSVDataset)...

                    INFO     Loading data from                                            ]8;id=918573;file:///home/viti/Documents/repos/harvard/optimuskg/.venv/lib/python3.12/site-packages/kedro/io/kedro_data_catalog.py\kedro_data_catalog.py]8;;\:]8;id=605850;file:///home/viti/Documents/repos/harvard/optimuskg/.venv/lib/python3.12/site-packages/kedro/io/kedro_data_catalog.py#757\757]8;;\
                             silver.reactome.pathway_protein_interactions (CSVDataset)...

In [71]:
ee_nodes = pl.concat(
    [
        ctd_exposure_exposure_interactions.select(
            pl.col("x_id").alias("id"),
            pl.col("x_type").alias("type"),
            pl.col("x_name").alias("name"),
            pl.col("x_source").alias("source"),
        ),
        ctd_exposure_exposure_interactions.select(
            pl.col("y_id").alias("id"),
            pl.col("y_type").alias("type"),
            pl.col("y_name").alias("name"),
            pl.col("y_source").alias("source"),
        ),
    ],
    how="vertical",
)

ep_nodes = ctd_exposure_protein_interactions.select(
    pl.col("y_id").alias("id"),
    pl.col("y_type").alias("type"),
    pl.col("y_name").alias("name"),
    pl.col("y_source").alias("source"),
)

all_nodes = pl.concat(
    [
        ee_nodes,
        ep_nodes,
    ],
    how="vertical",
)

all_nodes.filter(pl.col("type") == "exposure").unique()

shape: (698, 4)
┌──────────────┬──────────┬─────────────────────────────────┬────────┐
│ id           ┆ type     ┆ name                            ┆ source │
│ ---          ┆ ---      ┆ ---                             ┆ ---    │
│ str          ┆ str      ┆ str                             ┆ str    │
╞══════════════╪══════════╪═════════════════════════════════╪════════╡
│ MESH:D014805 ┆ exposure ┆ Vitamin B 12                    ┆ CTD    │
│ MESH:D011847 ┆ exposure ┆ Radioactive Fallout             ┆ CTD    │
│ MESH:C007477 ┆ exposure ┆ dimethyl phosphate              ┆ CTD    │
│ MESH:C034171 ┆ exposure ┆ di-n-pentyl phthalate           ┆ CTD    │
│ MESH:D017636 ┆ exposure ┆ Asbestos, Amphibole             ┆ CTD    │
│ …            ┆ …        ┆ …                               ┆ …      │
│ MESH:C555859 ┆ exposure ┆ 2,2',4,4',5,6'-hexabromodiphen… ┆ CTD    │
│ MESH:C028577 ┆ exposure ┆ monobutyl phthalate             ┆ CTD    │
│ MESH:C477779 ┆ exposure ┆ 2-hydroxyfluorene               ┆ CTD    │
│ MESH:D003035 ┆ exposure ┆ Cobalt                          ┆ CTD    │
│ MESH:C036042 ┆ exposure ┆ dicyclohexyl phthalate          ┆ CTD    │
└──────────────┴──────────┴─────────────────────────────────┴────────┘

In [90]:
ctd_exposure_exposure_nodes = (
    ctd_exposure_exposure_interactions.filter(pl.col("x_type") == "exposure")
    .select(
        pl.col("x_id").alias("id"),
        pl.col("x_type").alias("type"),
        pl.col("x_name").alias("name"),
        pl.col("x_source").alias("source"),
    )
    .unique()
)


ctd_exposure_exposure_interactions_x = (
    ctd_exposure_exposure_interactions.filter(pl.col("y_type") == "exposure")
    .select(
        pl.col("y_id").alias("id"),
        pl.col("y_type").alias("type"),
        pl.col("y_name").alias("name"),
        pl.col("y_source").alias("source"),
    )
    .unique()
)


ctd_exposure_protein_interactions = (
    ctd_exposure_protein_interactions.filter(pl.col("y_type") == "exposure")
    .select(
        pl.col("y_id").alias("id"),
        pl.col("y_type").alias("type"),
        pl.col("y_name").alias("name"),
        pl.col("y_source").alias("source"),
    )
    .unique()
)


pl.concat(
    [
        ctd_exposure_exposure_nodes,
        ctd_exposure_exposure_interactions_x,
        ctd_exposure_protein_interactions,
    ],
    how="vertical",
).unique()

╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ in <module>:36                                                                                   │
│                                                                                                  │
│   33 )                                                                                           │
│   34                                                                                             │
│   35                                                                                             │
│ ❱ 36 pl.concat([                                                                                 │
│   37 │   ctd_exposure_exposure_nodes,                                                            │
│   38 │   ctd_exposure_exposure_interactions_x,                                                   │
│   39 │   ctd_exposure_protein_interactions,                                                      │
│                                                                                                  │
│ /home/viti/Documents/repos/harvard/optimuskg/.venv/lib/python3.12/site-packages/polars/functions │
│ /eager.py:229 in concat                                                                          │
│                                                                                                  │
│   226 │                                                                                          │
│   227 │   if isinstance(first, pl.DataFrame):                                                    │
│   228 │   │   if how == "vertical":                                                              │
│ ❱ 229 │   │   │   out = wrap_df(plr.concat_df(elems))                                            │
│   230 │   │   elif how == "vertical_relaxed":                                                    │
│   231 │   │   │   out = wrap_ldf(                                                                │
│   232 │   │   │   │   plr.concat_lf(                                                             │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
AttributeError: 'tuple' object has no attribute '_df'

In [84]:
ctd_exposure_exposure_interactions.unique()

shape: (2_505, 10)
┌────────────┬────────────┬───────────┬──────────┬───┬───────────┬──────────┬───────────┬──────────┐
│ relation   ┆ display_re ┆ x_id      ┆ x_type   ┆ … ┆ y_id      ┆ y_type   ┆ y_name    ┆ y_source │
│ ---        ┆ lation     ┆ ---       ┆ ---      ┆   ┆ ---       ┆ ---      ┆ ---       ┆ ---      │
│ str        ┆ ---        ┆ str       ┆ str      ┆   ┆ str       ┆ str      ┆ str       ┆ str      │
│            ┆ str        ┆           ┆          ┆   ┆           ┆          ┆           ┆          │
╞════════════╪════════════╪═══════════╪══════════╪═══╪═══════════╪══════════╪═══════════╪══════════╡
│ exposure_e ┆ parent-chi ┆ MESH:D052 ┆ exposure ┆ … ┆ MESH:C027 ┆ exposure ┆ butylbenz ┆ CTD      │
│ xposure    ┆ ld         ┆ 244       ┆          ┆   ┆ 561       ┆          ┆ yl        ┆          │
│            ┆            ┆           ┆          ┆   ┆           ┆          ┆ phthalate ┆          │
│ exposure_e ┆ parent-chi ┆ MESH:C041 ┆ exposure ┆ … ┆ MESH:C017 ┆ exposure ┆ 3-phenoxy ┆ CTD      │
│ xposure    ┆ ld         ┆ 392       ┆          ┆   ┆ 618       ┆          ┆ benzoic   ┆          │
│            ┆            ┆           ┆          ┆   ┆           ┆          ┆ acid      ┆          │
│ exposure_e ┆ parent-chi ┆ MESH:D003 ┆ exposure ┆ … ┆ MESH:C034 ┆ exposure ┆ anthracen ┆ CTD      │
│ xposure    ┆ ld         ┆ 077       ┆          ┆   ┆ 020       ┆          ┆ e         ┆          │
│ exposure_e ┆ parent-chi ┆ MESH:D000 ┆ exposure ┆ … ┆ MESH:D011 ┆ exposure ┆ Polypropy ┆ CTD      │
│ xposure    ┆ ld         ┆ 080545    ┆          ┆   ┆ 126       ┆          ┆ lenes     ┆          │
│ exposure_e ┆ parent-chi ┆ MESH:D003 ┆ exposure ┆ … ┆ MESH:C092 ┆ exposure ┆ 1-hydroxy ┆ CTD      │
│ xposure    ┆ ld         ┆ 077       ┆          ┆   ┆ 102       ┆          ┆ phenanthr ┆          │
│            ┆            ┆           ┆          ┆   ┆           ┆          ┆ ene       ┆          │
│ …          ┆ …          ┆ …         ┆ …        ┆ … ┆ …         ┆ …        ┆ …         ┆ …        │
│ exposure_e ┆ parent-chi ┆ MESH:D007 ┆ exposure ┆ … ┆ MESH:D001 ┆ exposure ┆ Boron     ┆ CTD      │
│ xposure    ┆ ld         ┆ 220       ┆          ┆   ┆ 895       ┆          ┆           ┆          │
│ exposure_e ┆ parent-chi ┆ MESH:D052 ┆ exposure ┆ … ┆ MESH:D002 ┆ exposure ┆ Calcium   ┆ CTD      │
│ xposure    ┆ ld         ┆ 638       ┆          ┆   ┆ 118       ┆          ┆           ┆          │
│ exposure_e ┆ parent-chi ┆ MESH:D000 ┆ exposure ┆ … ┆ MESH:C018 ┆ exposure ┆ 2,4,5,2', ┆ CTD      │
│ xposure    ┆ ld         ┆ 083462    ┆          ┆   ┆ 566       ┆          ┆ 4',5'-hex ┆          │
│            ┆            ┆           ┆          ┆   ┆           ┆          ┆ abromobip ┆          │
│            ┆            ┆           ┆          ┆   ┆           ┆          ┆ hen…      ┆          │
│ exposure_e ┆ parent-chi ┆ MESH:D003 ┆ exposure ┆ … ┆ MESH:C581 ┆ exposure ┆ monoethyl ┆ CTD      │
│ xposure    ┆ ld         ┆ 358       ┆          ┆   ┆ 825       ┆          ┆ phthalate ┆          │
│ exposure_e ┆ parent-chi ┆ MESH:D005 ┆ exposure ┆ … ┆ MESH:D001 ┆ exposure ┆ Benzene   ┆ CTD      │
│ xposure    ┆ ld         ┆ 990       ┆          ┆   ┆ 554       ┆          ┆           ┆          │
└────────────┴────────────┴───────────┴──────────┴───┴───────────┴──────────┴───────────┴──────────┘