In [48]:
import re
import polars as pl

In [49]:
mondo_terms = catalog.load("bronze.ontology.mondo_terms")
mondo_xrefs = catalog.load("bronze.ontology.mondo_xrefs")
mrconso = catalog.load("bronze.umls.mrconso")

[06/13/25 18:49:51] INFO     Loading data from bronze.ontology.mondo_terms                ]8;id=338761;file:///home/viti/Documents/repos/personal/hardvard/optimuskg/.venv/lib/python3.12/site-packages/kedro/io/kedro_data_catalog.py\kedro_data_catalog.py]8;;\:]8;id=402137;file:///home/viti/Documents/repos/personal/hardvard/optimuskg/.venv/lib/python3.12/site-packages/kedro/io/kedro_data_catalog.py#757\757]8;;\
                             (CSVDataset)...

                    INFO     Loading data from bronze.ontology.mondo_xrefs                ]8;id=755529;file:///home/viti/Documents/repos/personal/hardvard/optimuskg/.venv/lib/python3.12/site-packages/kedro/io/kedro_data_catalog.py\kedro_data_catalog.py]8;;\:]8;id=830336;file:///home/viti/Documents/repos/personal/hardvard/optimuskg/.venv/lib/python3.12/site-packages/kedro/io/kedro_data_catalog.py#757\757]8;;\
                             (CSVDataset)...

                    INFO     Loading data from bronze.umls.mrconso (CSVDataset)...        ]8;id=867023;file:///home/viti/Documents/repos/personal/hardvard/optimuskg/.venv/lib/python3.12/site-packages/kedro/io/kedro_data_catalog.py\kedro_data_catalog.py]8;;\:]8;id=893821;file:///home/viti/Documents/repos/personal/hardvard/optimuskg/.venv/lib/python3.12/site-packages/kedro/io/kedro_data_catalog.py#757\757]8;;\

In [50]:
mondo_terms

shape: (30_204, 3)
┌───────────────┬─────────────────────────────────┬───────┐
│ id            ┆ name                            ┆ type  │
│ ---           ┆ ---                             ┆ ---   │
│ str           ┆ str                             ┆ str   │
╞═══════════════╪═════════════════════════════════╪═══════╡
│ MONDO_0005153 ┆ cervical adenocarcinoma         ┆ CLASS │
│ MONDO_0060631 ┆ Alkuraya-Kucinskas syndrome     ┆ CLASS │
│ MONDO_0002654 ┆ uterine disorder                ┆ CLASS │
│ MONDO_0700148 ┆ canine transitional cell carci… ┆ CLASS │
│ MONDO_0800314 ┆ xeroderma pigmentosum, type G/… ┆ CLASS │
│ …             ┆ …                               ┆ …     │
│ MONDO_0002329 ┆ testicular disorder             ┆ CLASS │
│ MONDO_0019576 ┆ telangiectasia macularis erupt… ┆ CLASS │
│ MONDO_0019230 ┆ inborn disorder of ornithine o… ┆ CLASS │
│ MONDO_0019294 ┆ mixed dermis disorder           ┆ CLASS │
│ MONDO_0016016 ┆ toluene embryopathy             ┆ CLASS │
└───────────────┴─────────────────────────────────┴───────┘

In [51]:
mondo_xrefs

shape: (134_206, 2)
┌───────────────┬─────────────────┐
│ id            ┆ xref_id         │
│ ---           ┆ ---             │
│ str           ┆ str             │
╞═══════════════╪═════════════════╡
│ MONDO_0957427 ┆ UMLS:C5816790   │
│ MONDO_0010662 ┆ OMIM:309560     │
│ MONDO_0041259 ┆ MEDGEN:509091   │
│ MONDO_0005769 ┆ NORD:1647       │
│ MONDO_0958185 ┆ OMIM:620300     │
│ …             ┆ …               │
│ MONDO_0013390 ┆ Orphanet:254361 │
│ MONDO_0006360 ┆ MEDGEN:208877   │
│ MONDO_0008003 ┆ MESH:C563575    │
│ MONDO_0015275 ┆ MESH:C536112    │
│ MONDO_0013471 ┆ DOID:0110513    │
└───────────────┴─────────────────┘

In [52]:
mrconso

shape: (11_434_670, 18)
┌──────────┬──────────┬─────────────┬───────────┬───┬───────────────────────┬─────┬─────────┬──────┐
│ cui      ┆ language ┆ term_status ┆ lui       ┆ … ┆ source_name           ┆ srl ┆ supress ┆ cvf  │
│ ---      ┆ ---      ┆ ---         ┆ ---       ┆   ┆ ---                   ┆ --- ┆ ---     ┆ ---  │
│ str      ┆ str      ┆ str         ┆ str       ┆   ┆ str                   ┆ str ┆ str     ┆ str  │
╞══════════╪══════════╪═════════════╪═══════════╪═══╪═══════════════════════╪═════╪═════════╪══════╡
│ C0000005 ┆ ENG      ┆ S           ┆ L0270109  ┆ … ┆ (131)I-MAA            ┆ 0   ┆ N       ┆ 256  │
│ C0000039 ┆ ENG      ┆ P           ┆ L0000039  ┆ … ┆ 1,2-dipalmitoylphosph ┆ 0   ┆ N       ┆ 256  │
│          ┆          ┆             ┆           ┆   ┆ atidylcho…            ┆     ┆         ┆      │
│ C0000039 ┆ ENG      ┆ P           ┆ L0000039  ┆ … ┆ 1,2-dipalmitoylphosph ┆ 0   ┆ N       ┆ 256  │
│          ┆          ┆             ┆           ┆   ┆ atidylcho…            ┆     ┆         ┆      │
│ C0000039 ┆ ENG      ┆ P           ┆ L0000039  ┆ … ┆ 1,2-Dipalmitoylphosph ┆ 0   ┆ N       ┆ null │
│          ┆          ┆             ┆           ┆   ┆ atidylcho…            ┆     ┆         ┆      │
│ C0000039 ┆ ENG      ┆ P           ┆ L0000039  ┆ … ┆ 1,2 Dipalmitoylphosph ┆ 0   ┆ N       ┆ null │
│          ┆          ┆             ┆           ┆   ┆ atidylcho…            ┆     ┆         ┆      │
│ …        ┆ …        ┆ …           ┆ …         ┆ … ┆ …                     ┆ …   ┆ …       ┆ …    │
│ C5441501 ┆ ENG      ┆ P           ┆ L16799616 ┆ … ┆ Unacceptable PDX      ┆ 0   ┆ N       ┆ null │
│ C5441502 ┆ ENG      ┆ P           ┆ L16799612 ┆ … ┆ Unacceptable DX1      ┆ 0   ┆ N       ┆ null │
│ C5441503 ┆ ENG      ┆ P           ┆ L16799615 ┆ … ┆ Musculoskeletal pain, ┆ 0   ┆ N       ┆ null │
│          ┆          ┆             ┆           ┆   ┆ not low …             ┆     ┆         ┆      │
│ C5441504 ┆ ENG      ┆ P           ┆ L16799631 ┆ … ┆ Medication Reference  ┆ 0   ┆ N       ┆ null │
│          ┆          ┆             ┆           ┆   ┆ Terminolo…            ┆     ┆         ┆      │
│ C5441504 ┆ ENG      ┆ S           ┆ L16799634 ┆ … ┆ MED-RT_2021_03_01     ┆ 0   ┆ N       ┆ null │
└──────────┴──────────┴─────────────┴───────────┴───┴───────────────────────┴─────┴─────────┴──────┘

In [53]:
mondo_xrefs = mondo_xrefs.filter(
    pl.col("xref_id").str.starts_with("UMLS:")
).with_columns(pl.col("xref_id").str.replace("UMLS:", "").alias("xref_id"))
mondo_xrefs

shape: (21_272, 2)
┌───────────────┬──────────┐
│ id            ┆ xref_id  │
│ ---           ┆ ---      │
│ str           ┆ str      │
╞═══════════════╪══════════╡
│ MONDO_0957427 ┆ C5816790 │
│ MONDO_0021453 ┆ C0154027 │
│ MONDO_0044200 ┆ C5679894 │
│ MONDO_0045047 ┆ C0393485 │
│ MONDO_0004243 ┆ C1520093 │
│ …             ┆ …        │
│ MONDO_0009741 ┆ C2749485 │
│ MONDO_0015935 ┆ C5190513 │
│ MONDO_0001629 ┆ C0152084 │
│ MONDO_0030978 ┆ C5543128 │
│ MONDO_0054726 ┆ C4540179 │
└───────────────┴──────────┘

In [54]:
df_umls = mrconso.select(
    ["cui", "source_cui", "source_descriptor_dui", "abbreviated_source", "source_code"]
).unique()
df_umls.select(["abbreviated_source"]).unique()

shape: (146, 1)
┌────────────────────┐
│ abbreviated_source │
│ ---                │
│ str                │
╞════════════════════╡
│ NCI_NCI-HL7        │
│ PDQ                │
│ CCSR_ICD10PCS      │
│ HPO                │
│ NCI_JAX            │
│ …                  │
│ NIC                │
│ NCI_BRIDG_3_0_3    │
│ PSY                │
│ CSP                │
│ MEDLINEPLUS        │
└────────────────────┘

In [56]:
df_umls = df_umls.join(
    mondo_xrefs, left_on="source_cui", right_on="id", how="inner", suffix="_cui"
)
# df_umls = df_umls.join(
#     mondo_xrefs,
#     left_on="source_descriptor_dui",
#     right_on="id",
#     how="inner",
#     suffix="_dui"
# )
# df_umls = df_umls.join(
#     mondo_xrefs,
#     left_on="source_code",
#     right_on="id",
#     how="inner",
#     suffix="_code"
# )
df_umls = df_umls.unique()
df_umls

shape: (0, 10)
┌─────┬────────────┬────────────┬────────────┬───┬────────────┬────────────┬───────────┬───────────┐
│ cui ┆ source_cui ┆ source_des ┆ abbreviate ┆ … ┆ xref_id_ri ┆ xref_id_cu ┆ xref_id_d ┆ xref_id_c │
│ --- ┆ ---        ┆ criptor_du ┆ d_source   ┆   ┆ ght        ┆ i          ┆ ui        ┆ ode       │
│ str ┆ str        ┆ i          ┆ ---        ┆   ┆ ---        ┆ ---        ┆ ---       ┆ ---       │
│     ┆            ┆ ---        ┆ str        ┆   ┆ str        ┆ str        ┆ str       ┆ str       │
│     ┆            ┆ str        ┆            ┆   ┆            ┆            ┆           ┆           │
╞═════╪════════════╪════════════╪════════════╪═══╪════════════╪════════════╪═══════════╪═══════════╡
└─────┴────────────┴────────────┴────────────┴───┴────────────┴────────────┴───────────┴───────────┘

In [47]:
pairs = [
    ("OMIM", "OMIM"),
    ("NCI", "NCIT"),
    ("MSH", "MESH"),
    ("MDR", "MedDRA"),
    ("ICD10", "ICD10"),
    ("SNOMEDCT_US", "SCTID"),
]

valid = []
for abbreviated_source, ontology in pairs:
    source_matches = df_umls.filter(pl.col("abbreviated_source") == abbreviated_source)

    matches = source_matches.join(
        mondo_xrefs, left_on="source_code", right_on="xref_id", how="inner"
    ).select(
        [
            pl.lit(abbreviated_source).alias("abbreviated_source"),
            pl.lit(ontology).alias("ontology"),
            pl.col("source_code"),
            pl.col("id"),
        ]
    )

    valid.append(matches)

# Combine all matches into a single dataframe
valid_df = pl.concat(valid)
valid_df

shape: (0, 4)
┌────────┬──────────┬─────────────┬─────┐
│ source ┆ ontology ┆ source_code ┆ id  │
│ ---    ┆ ---      ┆ ---         ┆ --- │
│ str    ┆ str      ┆ str         ┆ str │
╞════════╪══════════╪═════════════╪═════╡
└────────┴──────────┴─────────────┴─────┘